Clarification de la table « computed substances »
betagouv/complements-alimentaires pull request #1001
Opened 2024-09-16 13:19 UTC by alemangui

Closes #997 

Cette PR fait deux choses :
- Enlève les colonnes « CAS » et « EINEC », très peu utilisées et gênantes pour la lecture de la ligne
- Le titre est passé de « Substances » à « Dosage totale des substances actives »
- Le texte a été divisé en deux lignes pour faciliter la lecture, laissant dans une linge toute seule l'instruction « Veuillez compléter leur dosage total. »

![image](https://github.com/user-attachments/assets/8e4bf659-7b6d-45e5-881c-77cce7957853)

2024-09-17 07:55 UTC, pletelli commented on frontend/src/views/ProducerFormPage/CompositionTab.vue
> +        content="Les substances contenues dans les ingrédients actifs renseignés sont affichées ci-dessous. Veuillez compléter leur dosage total."
Sur Tchap la discussion entre @Fantine-py et Emmanuelle, proposait plutôt : 

V1
"Ce tableau présente les substances actives identifiées dans les ingrédients que vous avez sélectionnés. Etant donné qu'une même substance peut être introduite par plusieurs sources, nous vous demandons de renseigner pour chaque substance la quantité totale par dose journalière recommandée (DJR)."

V2
"Ce tableau présente les substances actives identifiées dans les ingrédients que vous avez sélectionnés.
Une même substance pouvant être introduite par plusieurs sources, nous vous demandons de renseigner pour chaque substance la quantité totale par dose journalière recommandée (DJR)."

2024-09-17 07:56 UTC, pletelli requested changes

2024-09-17 07:56 UTC, pletelli commented on frontend/src/views/ProducerFormPage/CompositionTab.vue
> +        content="Les substances contenues dans les ingrédients actifs renseignés sont affichées ci-dessous. Veuillez compléter leur dosage total."
Vu avec elles ?

Sinon dans le `title` : Dosage total~~E~~ des substances actives"

2024-09-17 07:57 UTC, pletelli commented on frontend/src/views/ProducerFormPage/CompositionTab.vue
> +        content="Les substances contenues dans les ingrédients actifs renseignés sont affichées ci-dessous. Veuillez compléter leur dosage total."
Et le texte "Veuillez compléter leur dosage total" n'est pas sur une ligne indépendante.

2024-09-17 15:10 UTC, alemangui commented on frontend/src/views/ProducerFormPage/CompositionTab.vue
> +        content="Les substances contenues dans les ingrédients actifs renseignés sont affichées ci-dessous. Veuillez compléter leur dosage total."
Merci Perrine, j'ai changé ces éléments ici : https://github.com/betagouv/complements-alimentaires/pull/1001/commits/e471d9fd8f991a4be19aa1eb03404d26bbcd7f47

![image](https://github.com/user-attachments/assets/2f7f7966-f7d5-4d8f-aa9f-91a206deef24)

2024-09-20 08:32 UTC, pletelli approved these changes

2024-09-20 08:32 UTC, merged