Make declaredsubstances addable in back and front
betagouv/complements-alimentaires pull request #1003
Opened 2024-09-17 09:46 UTC by pletelli

2024-09-24 14:36 UTC, alemangui requested changes

2024-09-24 14:36 UTC, alemangui commented on frontend/src/views/ProducerFormPage/ElementCard.vue
> +              v-model="model.unit"
Je ne suis pas sur de mon coup, mais je pense que le modèle ici n'a pas de `unit` côté backend.

J'imagine que le modèle est un `DeclaredSubstance`, qui a bien maintenant une propriété `quantity` ([ici](https://github.com/betagouv/complements-alimentaires/pull/1003/files#diff-a88d8304b4f4244788a10685b7aaea52753a4a4894362e25c20d1b032ee7a806R492)) mais je ne vois pas la propriété `unit`, qui pourant est bien présente dans le [DeclaredIngredient](https://github.com/betagouv/complements-alimentaires/pull/1003/files#diff-a88d8304b4f4244788a10685b7aaea52753a4a4894362e25c20d1b032ee7a806R470) par exemple. 

Est-ce qu'on a des substances qui n'ont pas de unité définie ? si c'est la cas il faudra ajouter cette unité au même titre que `DeclaredIngredient`, et la préremplir avec l'unité de la substance si elle est présente.

2024-09-24 14:59 UTC, pletelli commented on frontend/src/views/ProducerFormPage/ElementCard.vue
> +              v-model="model.unit"
fix ici : 9ee6bbf7041603decd9c789252b97dbd7d6a89d7

2024-09-25 07:23 UTC, alemangui commented on frontend/src/views/ProducerFormPage/ElementCard.vue
> +              v-model="model.unit"
Merci ! J'ai une dernière petite question... Dans le cas où la substance a bien une unité associée, est-ce qu'on pre-rempli côté front la propriété `unit` de `DeclaredSubstance` ?

Par ex aujourd'hui si j'ajoute Acide Cafféique j'ai l'unité figée :

![image](https://github.com/user-attachments/assets/e7e045bb-cbdc-448a-b272-ff93a23858e4)

Et donc côté données, le `DeclaredSubstance.unit` reste vide

![image](https://github.com/user-attachments/assets/aed9e96f-7c74-4d6a-a7e8-e82c24c5d73f)

Ce qui n'est pas le cas pour les nouvelles substances. Par ex celle-ci met bien l'unité à ce niveau :

![image](https://github.com/user-attachments/assets/91bca749-bdef-4f22-bb48-fa52a06108d9)

![image](https://github.com/user-attachments/assets/44b4caee-b401-40a7-8dd0-dae28411981d)

2024-09-26 12:46 UTC, pletelli commented on frontend/src/views/ProducerFormPage/ElementCard.vue
> +              v-model="model.unit"
Done ici 8fefdbce2162f11f5a33c38eee5b9fbc8d88f1f7

2024-09-26 12:46 UTC, pletelli commented on frontend/src/views/ProducerFormPage/ElementCard.vue
> +              v-model="model.unit"
Et j'ai ajouté le display des quantité dans le summary step

2024-09-26 12:52 UTC, alemangui approved these changes

2024-09-26 13:22 UTC, merged