Ajout de la Suisse et la Grande-Bretagne dans la liste de pays
betagouv/complements-alimentaires pull request #1183
Opened 2024-10-24 09:53 UTC by alemangui

Closes #1180 

## Scope

Ajout de la Suisse :switzerland: et la Grande-Bretagne :gb: dans la liste de pays avec leur code ISO 3166-1 alpha-2.

2024-10-24 16:04 UTC, pletelli requested changes

2024-10-24 16:04 UTC, pletelli commented on data/migrations/0099_alter_company_country_alter_declaration_country_and_more.py
> +            name='eu_reference_country',
Je ne suis pas sûre que la Suisse et les UK fonctionnent pour les articles 16 avec si ?
Le décret dit "mais légalement fabriqué ou commercialisé dans un autre Etat membre de l'Union européenne ou un autre Etat partie à l'accord sur l'Espace économique européen donne lieu à la procédure suivant"

2024-10-24 16:10 UTC, alemangui commented on data/migrations/0099_alter_company_country_alter_declaration_country_and_more.py
> +            name='eu_reference_country',
Très bonne remarque... il faudrait que les listes des pays pour la création de l'entreprise et l'article 16 soient différentes... Je regarde.

2024-10-25 13:39 UTC, alemangui commented on data/migrations/0099_alter_company_country_alter_declaration_country_and_more.py
> +            name='eu_reference_country',
Pour info : https://github.com/betagouv/complements-alimentaires/issues/1180#issuecomment-2437811029

2024-10-25 13:39 UTC, closed without merging