Squelette pour le formulaire ingrédient
betagouv/complements-alimentaires pull request #1237
Opened 2024-11-06 17:20 UTC by hfroot

Peut-être pour éviter des gros PRs, on peut trouver un découpage raisonnable

2025-02-03 14:15 UTC, hfroot commented
TODO

Split into creation outside of declaration, and creation and replacement
Split each big PR into front and back
Design API: creation; creation and replacement

Split out things that aren't in the current models
Put substance linking and synonym linking into later PRs

2025-02-11 17:55 UTC, hfroot commented on frontend/src/views/ElementForm/index.vue
> +              <!-- TODO: make tags deleteable -->
J'attends une réponse sur https://github.com/dnum-mi/vue-dsfr/issues/1035 avant d'avancer

2025-02-17 11:30 UTC, alemangui requested changes

2025-02-17 11:30 UTC, alemangui commented on frontend/src/views/ElementForm/index.vue
> +const EMPTY_SYNONYM = { name: "" }
On compte réutiliser cette constante ? Pourquoi pas mettre directement `{ name:  "" }` dans la ligne d'après ?

2025-02-17 11:30 UTC, alemangui commented on frontend/src/views/ElementForm/index.vue
> +              activeText="Authorisé"
```suggestion
              activeText="Autorisé"
```

2025-02-17 11:30 UTC, alemangui commented on frontend/src/views/ElementForm/index.vue
> +              inactiveText="Non authorisé"
```suggestion
              inactiveText="Non autorisé"
```

2025-02-17 13:25 UTC, alemangui approved these changes

2025-02-17 14:28 UTC, merged