Missing data boolean
betagouv/complements-alimentaires pull request #130
Opened 2024-01-17 17:18 UTC by pletelli

2024-01-19 10:30 UTC, alemangui requested changes

2024-01-19 10:30 UTC, alemangui commented on data/models/abstract_models.py
> +    missing_import_data = models.BooleanField(blank=True, null=True, editable=False, default=True)
Je me demande si ça ne serait pas mieux de mettre le défaut à `False`. 

Ces éléments seraient emmenés à terme à être créés de formes différentes qu'avec l'import csv (soit directement par les instructrices, soit avec d'aures imports, etc). Même aujourd'hui on pourrait en créer depuis l'admin ou une factory. 

Ça me semble donc plus simple de l'avoir par défaut `False` car seul l'import csv est concerné et donc peut le mettre à `True` si besoin. T'en penses quoi ?

2024-01-22 09:50 UTC, pletelli commented on data/models/abstract_models.py
> +    missing_import_data = models.BooleanField(blank=True, null=True, editable=False, default=True)
J'imaginais sans doute un boolean différent par source d'import là où tu en imagines un unique non ?
Dans l'idée où ce boolean serait spécifique aux csv siccrf, ça me va mieux qu'il soit à `True`, mais pour des peut-être mauvaises raisons notamment ça simplifie le code de l'import_csv.

2024-01-22 09:50 UTC, pletelli commented on data/models/abstract_models.py
> +    missing_import_data = models.BooleanField(blank=True, null=True, editable=False, default=True)
je veux bien ton retour, et je modifie si besoin.

2024-01-25 10:22 UTC, pletelli commented on data/models/abstract_models.py
> +    missing_import_data = models.BooleanField(blank=True, null=True, editable=False, default=True)
La valeur par défaut de `missing_import_data` est mise à `True` : 0f3b0704ce513687922ff31147f0a369582da3bd
Une fonction de verification des missing_data qui update le champ à `False` : 33ea7ad2c7984ed365ae8e6ac972b03f0682b4a6

2024-01-30 14:26 UTC, alemangui approved these changes

2024-01-30 15:02 UTC, merged