Option pour remplacer un ingrédient demandé par un ingrédient existant
betagouv/complements-alimentaires pull request #1334
Opened 2024-12-02 17:44 UTC by hfroot

Dans le scope : fonctionnalité pour trouver un ingrédient de même type et remplacer une demande avec.

Hors du scope : ajout de synonyme en même temps; remplacement d'une demande par un ingrédient d'autre type (par ex microorganisme avec plante), à faire à la main pour l'instant

2024-12-19 21:39 UTC, hfroot commented on api/serializers/declaration.py
> +class DeclaredElementNestedField:
Cette refacto avait du sens quand j'ai commencé la PR. Maintenant, elle paraît un peu hors scope mais je l'ai laissée dedans car je trouve que c'est cool quand même de ne pas dupliquer la logique de `create`

2024-12-19 21:42 UTC, hfroot commented on api/tests/test_declaration.py
> +            reverse("api:declared_element", kwargs={"pk": plant.id, "type": "plant"}), format="json"
Dans cette PR, j'ai du changer l'API de REST vers RPC pour avoir un meilleur contrôle sur les actions de demande de plus d'infos (fait dans une PR avant), refus (aussi dans une autre PR), et le remplacement (le cible de cette PR).

Pendant ce changement, j'ai remarqué que c'est possible de changer l'API pour reduire la duplication de code entre 4 types d'element et 4 actions par demande. Alors ici, on voit que j'ai remplacé l'`api:declared_plant` avec `api:declared_element... "type": "plant"`

2024-12-19 21:44 UTC, hfroot commented on api/tests/test_declaration.py
> +            reverse("api:declared_element_request_info", kwargs={"pk": microorganism.id, "type": "microorganism"}),
avec la refacto, un appel REST vers `api:declared_x` est devenu un appel vers `api:declared_x_action`

2024-12-19 21:44 UTC, hfroot commented on api/tests/test_declaration.py
> +    def test_reject_declared_element(self):
Il y avait pas un test pour le refus d'ingrédient avant

2024-12-19 21:45 UTC, hfroot commented on api/tests/test_declaration.py
> +    def test_replace_declared_plant(self):
enfin on arrive aux tests ajoutés pour vérifier la vraie nouvelle fonctionnalité de cette PR :tada:

2024-12-19 21:47 UTC, hfroot commented on api/urls.py
> +    path("declared-elements/<str:type>/<int:pk>", views.DeclaredElementView.as_view(), name="declared_element"),
maintenant le nouveau api c'est:

pour lire: `declared-elements/<type>/<id>`
pour prendre une decision: `declared-elements/<type>/<id>/<action name>`

(avant c'etait `declared-elements/<type en pluriel>/<id>` REST)

2024-12-19 21:52 UTC, hfroot commented on frontend/src/components/DeclarationSummary/index.vue
> +    <DsfrAlert v-if="replacedRequestsWithSubstances.length" type="warning" class="mb-4">
est-ce que c'est un pb que cet avertissement va rester même après l'aller-retour instructrice - déclarant - instructrice ?

2024-12-19 21:59 UTC, hfroot commented on frontend/src/components/ElementAutocomplete.vue
> +    <div :class="hideSearchButton ? '' : 'flex items-end'">
avant, quand `hideSearchButton` est `false` le label du champ `DsfrInput` (quand donné) est affiché à côté du champ et non pas au dessus. Ce changement repare ça

2024-12-19 22:01 UTC, hfroot commented on frontend/src/views/DeclaredElementPage/ElementAlert.vue
> +<template>
Pendant une refacto, j'ai créé ce fichier pour améliorer le focus du code principal dans `index.vue`

2024-12-27 15:20 UTC, alemangui requested changes

2024-12-27 15:20 UTC, alemangui commented on api/serializers/declaration.py
> +                    field_errors={f"declared_{self.nested_field_name}s": "L'ingrédient spécifiée n'existe pas."}
Il faudra adapter aussi le message de l'exception non ? Genre 
```python
field_errors={f"declared_{self.nested_field_name}s": f"L'objet « ${self.nested_field_name} » spécifiée n'existe pas."}
```

2024-12-27 15:20 UTC, alemangui commented on api/tests/test_declaration.py
> +            reverse("api:declared_element", kwargs={"pk": plant.id, "type": "plant"}), format="json"
D'accord avec toi, ces actions semblent être plus transactionnelles qu'autre chose, du coup une approche RPC me semble plus adapté :+1:

2024-12-27 15:20 UTC, alemangui commented on api/tests/test_declaration.py
> +
Est-ce que ça vaut la peine d'ajouter un test sur les permissions pour ces nouveaux endpoints ? Similaire à `test_get_declared_element_not_allowed_not_instructor`

2024-12-27 15:20 UTC, alemangui commented on frontend/src/components/DeclarationSummary/index.vue
> +    <DsfrAlert v-if="replacedRequestsWithSubstances.length" type="warning" class="mb-4">
Peut-être on pourra ajuster le message :thinking: 

« Les ingrédients suivantes, ajoutés pour remplacer une demande, rajoutent des substances dans la composition.
Veuillez vérifier que les doses totales des substances restent pertinentes. »

Ou enfin qqchose du genre, sans forcément dire qu'il faut toujours contacter le pro.

2024-12-27 15:20 UTC, alemangui commented on frontend/src/components/ElementAutocomplete.vue
> +  optional: {
Est-ce que ça serait plus cohérent avec l'API des inputs de le nommer `required` ? et donc par la suite dans la ligne 11 `:required="required"`.

Surtout que de cette façon les autres composants utilisant `ElementAutocomplete` et n'envoyant pas explicitement la prop se retrouveront avec un changement de comportement : leur champ deviendra obligatoire.

2024-12-27 15:20 UTC, alemangui commented on frontend/src/views/DeclaredElementPage/ResultCard.vue
> +      <!-- TODO: make this a tag and align with badges, check DSFR -->
D'ailleurs on essaie de faire les commentaires en français dans le code. On n'est pas non plus hyper strictes mais p-e pour les prochains mieux de le faire en FR pour avoir une certaine cohérence.

2024-12-27 15:20 UTC, alemangui commented on frontend/src/views/DeclaredElementPage/index.vue
> +                  Veuillez contacter l'équipe Compl'Alim pour résoudre le substitution.
```suggestion
                  Veuillez contacter l'équipe Compl'Alim pour effectuer la substitution.
```

2024-12-27 15:20 UTC, alemangui commented on frontend/src/views/DeclaredElementPage/index.vue
> +  // TODO: is this handling errors nicely?
On peut le tester en envoyant un BadRequest programmatiquement, si tu veux on peut regarder ensemble

2025-01-06 08:07 UTC, hfroot commented on frontend/src/components/DeclarationSummary/index.vue
> +    <DsfrAlert v-if="replacedRequestsWithSubstances.length" type="warning" class="mb-4">
Je veux inclure une consigne pour rappeler comment resoudre le pb si les doses ne sont pas bons, tu penses quoi du suivant ?

![Screenshot 2025-01-06 at 09-02-31 Instruction - Compl'Alim](https://github.com/user-attachments/assets/a5b47f46-82ff-461f-a28d-cace7649c6e0)

(j'ai remarqué en même temps qu'il faut avoir un titre pour toutes les alertes quand l'ecran >= md)

2025-01-06 08:14 UTC, hfroot commented on frontend/src/components/ElementAutocomplete.vue
> +  optional: {
avant il y avait `:required="true"` alors il y a pas de difference de comportement avec le changement telquel, mais oui je vais changer le prop pour utiliser plutôt `required`

2025-01-06 08:45 UTC, hfroot commented on frontend/src/views/DeclaredElementPage/index.vue
> +  // TODO: is this handling errors nicely?
ah bien sûr, j'ai fait une petite modif suite au test

2025-01-06 12:54 UTC, hfroot commented on api/serializers/declaration.py
> +                    field_errors={f"declared_{self.nested_field_name}s": "L'ingrédient spécifiée n'existe pas."}
l'erreur sera :

```
fieldErrors: {
    declaredPlants: "L'ingrédient specifiée n'existe pas"
}
```

je trouve que c'est assez clair vu qu'on voit `declaredPlants` ?

J'ajoute quand même l'id de l'ingrédient qui n'existe pas.

Je MAJ le test pour rendre l'output explicit

2025-01-06 16:11 UTC, alemangui approved these changes

2025-01-06 16:11 UTC, alemangui commented on frontend/src/components/DeclarationSummary/index.vue
> +        Les ingrédients suivantes, ajoutés pour remplacer une demande, rajoutent des substances dans la composition.
```suggestion
        Les ingrédients suivants, ajoutés pour remplacer une demande, rajoutent des substances dans la composition.
```

2025-01-07 09:41 UTC, merged