Notebooks
betagouv/complements-alimentaires pull request #138
Opened 2024-01-23 08:20 UTC by pletelli

Cette PR :

- [x] ajoute un dossier de notebooks jupyter pour faire des analyses exploratoires des données
- [x] ajoute un notebook de calcul du pourcentage de complétion des champs "commentaires" et "descriptions" (réponse à la PR #110 )
- [x] ajoute un notebook pour préparer le séminaire de janvier : classification des contenu des champs commentaires (pour faire suite à l'étude https://github.com/betagouv/complements-alimentaires/issues/56#issuecomment-1902620282
- [x] ajoute un fichier requirements.txt specifique à l'analyse de données : requirements_notebooks.txt. L'idée est de ne pas avoir à installer ces dépendances sur les environnements de staging, prod

Cette branche peut :
* être mergée dans staging
* ou continuer à vivre en parallèle

Les notebooks sont visualisables directement dans github https://github.com/betagouv/complements-alimentaires/blob/notebooks/notebooks/siccrf_field_cleaning.ipynb

Pour comprendre le clustering de documents textuels (dans notre cas, les commentaires publics) l'[article](https://blog.christianperone.com/2011/10/machine-learning-text-feature-extraction-tf-idf-part-ii/) est très détaillé.

2024-01-24 14:00 UTC, alemangui requested changes

2024-01-24 14:00 UTC, alemangui commented on requirements.txt
> +pillow==10.2.0
Normalement c'est avec une P majuscule non ? :thinking: https://pillow.readthedocs.io/en/latest/installation.html

Certains posts SO ont l'air de suggérer aussi de l'installer en tant que `Pillow` (par ex [celui-ci](https://stackoverflow.com/questions/66996373/cant-import-pil-after-installing-pillow-with-poetry))

2024-01-24 14:00 UTC, alemangui commented on notebooks/siccrf_field_cleaning.ipynb
> +            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAjsAAAHHCAYAAABZbpmkAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjguMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8g+/7EAAAACXBIWXMAAA9hAAAPYQGoP6dpAABuY0lEQ
J'ai un `IndexError` de ce coté sur https://github.com/betagouv/complements-alimentaires/blob/notebooks/notebooks/siccrf_field_cleaning.ipynb (ci dessous)

D'ailleurs au sujet des erreurs plus généralement, sur celui-ci on peut voir le path local de ton ordi, ce n'est pas gravissime mais peut-être que les notebooks qu'on mettra sur GH devraient être buildés de sorte à ne pas donner une stack-trace ni ce type d'infos ?

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/home/perrine/Documents/Code/DINUM/complements-alimentaires/notebooks/siccrf_field_cleaning.ipynb Cell 22 line 2
     <a href='vscode-notebook-cell:/home/perrine/Documents/Code/DINUM/complements-alimentaires/notebooks/siccrf_field_cleaning.ipynb#X56sZmlsZQ%3D%3D?line=23'>24</a>     for i, txt in enumerate(count_vectorizer_without_stopW.get_feature_names_out()):
     <a href='vscode-notebook-cell:/home/perrine/Documents/Code/DINUM/complements-alimentaires/notebooks/siccrf_field_cleaning.ipynb#X56sZmlsZQ%3D%3D?line=24'>25</a>         ax[1].annotate(txt, (tsne[idx, 0][i], tsne[idx, 1][i]))
---> <a href='vscode-notebook-cell:/home/perrine/Documents/Code/DINUM/complements-alimentaires/notebooks/siccrf_field_cleaning.ipynb#X56sZmlsZQ%3D%3D?line=27'>28</a> plot_tsne_pca(tf_idf_matrix, clusters)

/home/perrine/Documents/Code/DINUM/complements-alimentaires/notebooks/siccrf_field_cleaning.ipynb Cell 22 line 2
     <a href='vscode-notebook-cell:/home/perrine/Documents/Code/DINUM/complements-alimentaires/notebooks/siccrf_field_cleaning.ipynb#X56sZmlsZQ%3D%3D?line=22'>23</a> ax[1].set_title('TSNE Cluster Plot')
     <a href='vscode-notebook-cell:/home/perrine/Documents/Code/DINUM/complements-alimentaires/notebooks/siccrf_field_cleaning.ipynb#X56sZmlsZQ%3D%3D?line=23'>24</a> for i, txt in enumerate(count_vectorizer_without_stopW.get_feature_names_out()):
---> <a href='vscode-notebook-cell:/home/perrine/Documents/Code/DINUM/complements-alimentaires/notebooks/siccrf_field_cleaning.ipynb#X56sZmlsZQ%3D%3D?line=24'>25</a>     ax[1].annotate(txt, (tsne[idx, 0][i], tsne[idx, 1][i]))

IndexError: index 300 is out of bounds for axis 0 with size 300
```

2024-01-24 14:00 UTC, alemangui commented on notebooks/siccrf_field_cleaning.ipynb
Question plus générale, comment veut-on gérer les warnings ? Il y en a quelques unes qui prennent pas mal de place (par ex les différents `SettingWithCopyWarning` sur https://github.com/betagouv/complements-alimentaires/blob/notebooks/notebooks/siccrf_field_cleaning.ipynb). Possible/souhaitable de builder sans ?

2024-01-24 14:00 UTC, alemangui commented
À mon avis on peut le mettre sur `staging` / `main` de sorte que ça co-existe avec le code.

2024-01-24 17:14 UTC, alemangui commented on requirements.txt
> +pillow==10.2.0
Bizarrement ça me le fait automatiquement aussi dès que je fais un pip freeze... p-e un changement de nom automatique.

2024-01-30 14:46 UTC, pletelli commented on notebooks/siccrf_field_cleaning.ipynb
Je l'ai juste géré en intégrant en début de notebook

```
import warnings
warnings.filterwarnings("ignore")

```
et en corrigeant l'erreur.

J'aurais aimé trouver une solution automatique plus satisfaisante et inspirée de : 

- https://github.com/toobaz/ipynb_output_filter qui utilise un script de cleaning (en le modifiant pour ne supprimer que les warning et erreurs au lieu de toute la cellule) mais l'inconvénient se situe sur le changement de branche et la conservation des outputs.
- https://zhauniarovich.com/post/2020/2020-06-clearing-jupyter-output/ qui utilise pre-commit et nbconvert pour supprimer complètement les outputs (mais nbconvert n'a pas d'option pour effacer juste les erreurs et warning)

La solution de n'exporter que le html ne convient pas, car les warning et erreurs restent dans le html.

2024-01-30 15:50 UTC, pletelli commented on notebooks/siccrf_field_cleaning.ipynb
> +            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAjsAAAHHCAYAAABZbpmkAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjguMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8g+/7EAAAACXBIWXMAAA9hAAAPYQGoP6dpAABuY0lEQ
résolu dans 4a46c3ead3985efa6bd93216f7ff524a520f7ceb

2024-01-30 15:50 UTC, merged