Ajout des pages légales : « CGU », « mentions légales » et « politique de confidentialité »
betagouv/complements-alimentaires pull request #189
Opened 2024-02-07 14:57 UTC by alemangui

## Pages Vue

Une page et une route a été créé pour chaque document. Le corps a été pris de ces [documents Notion](https://www.notion.so/betagouv-dinum/Pages-footer-CGU-mentions-l-gales-8589ecc1fd4f4894a6bd6b9253862492).

## Footer

En plus de l'ajout des pages, on trouve désormais ces liens dans le footer :

![image](https://github.com/betagouv/complements-alimentaires/assets/1225929/654994b4-29b9-48c7-abec-d81c2114ccfb)

2024-02-07 16:42 UTC, pletelli requested changes
ça m'irait de merger comme ça.
Mais la modif ne me semble pas très coûteuse.


Je trouve surtout drôle que sur [cette page du gouv](https://www.francenum.gouv.fr/guides-et-conseils/developpement-commercial/site-web/rediger-des-conditions-generales-dutilisation) pour nous aider à définir des CGU, il n'y ait pas de CGU dans le footer :eye:

2024-02-07 16:42 UTC, pletelli commented on frontend/src/App.vue
> +const footerLinks = [
comme je comprends les mandatory-links sur le DSFR [ici](https://vue-dsfr.netlify.app/?path=/docs/composants-dsfrfooter--docs) et [ici](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/pied-de-page/)
J'ai l'impression que ça ne peut pas être d'autres labels que :
* Accessibilité (nous ne l'avons pas encore)
* Mentions légales
* Données personnelles (notre politique de confidentialité)
* Gestion des cookies (contenu dans notre politique de confidentialité)
Du coup je mettrais peut-être les CGU dans `afterMandatoryLinks`

2024-02-07 16:44 UTC, pletelli commented on frontend/src/views/CGU.vue
> +    <h2>Mentions légales</h2>
Doublon ? avec les mentions légales ?

2024-02-07 16:53 UTC, alemangui commented on frontend/src/views/CGU.vue
> +    <h2>Mentions légales</h2>
Oui un peu, je me suis basé sur le premier set des documents légaux de ma cantine. Là dessus le service légale avait quand même mis cette section dans les CGU comme un résumé malgré la page plus complète à coté. Éventuellement je peut rajouter un lien après le `<p>` qui linkerait vers nos mentions légales plus complètes

2024-02-07 16:56 UTC, alemangui commented on frontend/src/views/CGU.vue
> +    <h2>Mentions légales</h2>
![image](https://github.com/betagouv/complements-alimentaires/assets/1225929/de558b5c-8404-4354-9637-2c9de6997ca7)
 Fix : https://github.com/betagouv/complements-alimentaires/pull/189/commits/97eacb7ef7dc2b35b6ef14952cbc92ab136994b0

2024-02-07 17:05 UTC, pletelli commented on frontend/src/views/CGU.vue
> +    <h2>Mentions légales</h2>
Parfait pour moi !

2024-02-07 17:12 UTC, alemangui commented on frontend/src/App.vue
> +const footerLinks = [
Fix ici : https://github.com/betagouv/complements-alimentaires/pull/189/commits/abb1cbdd752ff1c43b8ab3dc5af1c5fcb0236c95

J'ai aussi ajouté un issue pour la page a11y : [192](https://github.com/betagouv/complements-alimentaires/issues/192)

2024-02-09 08:36 UTC, pletelli commented on frontend/src/App.vue
> +  >
:+1:

2024-02-09 08:37 UTC, pletelli approved these changes

2024-02-09 08:37 UTC, merged