Ajout de Poetry comme package manager
betagouv/complements-alimentaires pull request #221
Opened 2024-02-16 12:28 UTC by ddahan

### Gains attendus
cf. #208

### Notes
- Pour le versionning des packages, on part du principe de vouloir les dernières versions (avec la syntaxe `*`), sauf pour Python et Django où la mise à jour sera un travail manuel
- À priori, on ne peut malheureusement pas spécifier à Clevercloud comment installer le projet directement avec Poetry. Cela nous force à être capable de générer un fichier `requirements.txt` à partir de Poetry, juste pour Clevercloud. Pour cela : // FIXME
- En conséquence, il faut bien penser à ne plus modifier ce fichier directement, car il sera écrasé. La commande `pip install` ne doit plus être utilisée.
- Pour simplifier l'installation, `pre-commit` a été mis en package "normal".
- les `requirements_notebook.txt` ont été mis en dev dependencies, c'est à dire qu'ils ne seront pas installées sur les environnements clevercloud. Cela peut être changé si besoin.

### Code Review et tests post review
- Vérifier que le passage du pre-commit dans un package local ne pose pas de soucis (ok pour moi en local).
- Au delà de la CR du code, Il est fort probable qu'il y ait un package oublié quelque part. Il faudrait pour cela essayer de faire un test poussé des différentes features du projet sur staging, avant un passage en prod. A noter que ces packages n'ont pas été réinstallés car ils ne semblent pas utiliser dans le projet : aiohttp, async-timeout, tomli, typing-extensions.
- Est-ce que dependabot fonctionne toujours comme voulu ?

### Sauvegarde de l'état actuel

Snapshot de `pipdeptree` avant la mise à jour, pour débuguer plus facilement par la suite si nécessaire :
```
aiohttp==3.9.3
├── aiosignal [required: >=1.1.2, installed: 1.3.1]
│   └── frozenlist [required: >=1.1.0, installed: 1.4.1]
├── attrs [required: >=17.3.0, installed: 23.2.0]
├── frozenlist [required: >=1.1.1, installed: 1.4.1]
├── multidict [required: >=4.5,<7.0, installed: 6.0.5]
└── yarl [required: >=1.0,<2.0, installed: 1.9.4]
    ├── idna [required: >=2.0, installed: 3.6]
    └── multidict [required: >=4.0, installed: 6.0.5]
async-timeout==4.0.3
black==24.1.1
├── click [required: >=8.0.0, installed: 8.1.7]
├── mypy-extensions [required: >=0.4.3, installed: 1.0.0]
├── packaging [required: >=22.0, installed: 23.2]
├── pathspec [required: >=0.9.0, installed: 0.12.1]
└── platformdirs [required: >=2, installed: 3.11.0]
boto3==1.34.29
├── botocore [required: >=1.34.29,<1.35.0, installed: 1.34.29]
│   ├── jmespath [required: >=0.7.1,<2.0.0, installed: 1.0.1]
│   ├── python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.2]
│   │   └── six [required: >=1.5, installed: 1.16.0]
│   └── urllib3 [required: >=1.25.4,<2.1, installed: 2.0.7]
├── jmespath [required: >=0.7.1,<2.0.0, installed: 1.0.1]
└── s3transfer [required: >=0.10.0,<0.11.0, installed: 0.10.0]
    └── botocore [required: >=1.33.2,<2.0a.0, installed: 1.34.29]
        ├── jmespath [required: >=0.7.1,<2.0.0, installed: 1.0.1]
        ├── python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.2]
        │   └── six [required: >=1.5, installed: 1.16.0]
        └── urllib3 [required: >=1.25.4,<2.1, installed: 2.0.7]
django-anymail==10.2
├── cryptography [required: Any, installed: 42.0.2]
│   └── cffi [required: >=1.12, installed: 1.16.0]
│       └── pycparser [required: Any, installed: 2.21]
├── Django [required: >=2.0, installed: 5.0.2]
│   ├── asgiref [required: >=3.7.0,<4, installed: 3.7.2]
│   └── sqlparse [required: >=0.3.1, installed: 0.4.4]
├── requests [required: >=2.4.3, installed: 2.31.0]
│   ├── certifi [required: >=2017.4.17, installed: 2024.2.2]
│   ├── charset-normalizer [required: >=2,<4, installed: 3.3.2]
│   ├── idna [required: >=2.5,<4, installed: 3.6]
│   └── urllib3 [required: >=1.21.1,<3, installed: 2.0.7]
└── urllib3 [required: >=1.25.0, installed: 2.0.7]
django-ckeditor==6.7.0
├── Django [required: >=3.2, installed: 5.0.2]
│   ├── asgiref [required: >=3.7.0,<4, installed: 3.7.2]
│   └── sqlparse [required: >=0.3.1, installed: 0.4.4]
└── django-js-asset [required: >=2.0, installed: 2.2.0]
    └── Django [required: >=3.2, installed: 5.0.2]
        ├── asgiref [required: >=3.7.0,<4, installed: 3.7.2]
        └── sqlparse [required: >=0.3.1, installed: 0.4.4]
django-environ==0.11.2
django-filter==23.5
└── Django [required: >=3.2, installed: 5.0.2]
    ├── asgiref [required: >=3.7.0,<4, installed: 3.7.2]
    └── sqlparse [required: >=0.3.1, installed: 0.4.4]
django-simple-history==3.4.0
django-storages==1.14.2
└── Django [required: >=3.2, installed: 5.0.2]
    ├── asgiref [required: >=3.7.0,<4, installed: 3.7.2]
    └── sqlparse [required: >=0.3.1, installed: 0.4.4]
django-webpack-loader==3.0.0
djangorestframework-camel-case==1.4.2
drf-base64==2.0
├── Django [required: >=2.0, installed: 5.0.2]
│   ├── asgiref [required: >=3.7.0,<4, installed: 3.7.2]
│   └── sqlparse [required: >=0.3.1, installed: 0.4.4]
└── djangorestframework [required: <4.0.0, installed: 3.14.0]
    ├── Django [required: >=3.0, installed: 5.0.2]
    │   ├── asgiref [required: >=3.7.0,<4, installed: 3.7.2]
    │   └── sqlparse [required: >=0.3.1, installed: 0.4.4]
    └── pytz [required: Any, installed: 2023.3.post1]
factory-boy==3.3.0
└── Faker [required: >=0.7.0, installed: 22.2.0]
    └── python-dateutil [required: >=2.4, installed: 2.8.2]
        └── six [required: >=1.5, installed: 1.16.0]
pillow==10.2.0
pip==24.0
pipdeptree==2.13.2
pre-commit==3.6.0
├── cfgv [required: >=2.0.0, installed: 3.4.0]
├── identify [required: >=1.0.0, installed: 2.5.33]
├── nodeenv [required: >=0.11.1, installed: 1.8.0]
│   └── setuptools [required: Any, installed: 65.5.1]
├── PyYAML [required: >=5.1, installed: 6.0.1]
└── virtualenv [required: >=20.10.0, installed: 20.25.0]
    ├── distlib [required: >=0.3.7,<1, installed: 0.3.8]
    ├── filelock [required: >=3.12.2,<4, installed: 3.13.1]
    └── platformdirs [required: >=3.9.1,<5, installed: 3.11.0]
psycopg2==2.9.9
pylint-django==2.5.5
├── pylint [required: >=2.0,<4, installed: 3.0.3]
│   ├── astroid [required: >=3.0.1,<=3.1.0-dev0, installed: 3.0.2]
│   ├── dill [required: >=0.3.6, installed: 0.3.8]
│   ├── isort [required: >=4.2.5,<6,!=5.13.0, installed: 5.13.2]
│   ├── mccabe [required: >=0.6,<0.8, installed: 0.7.0]
│   ├── platformdirs [required: >=2.2.0, installed: 3.11.0]
│   └── tomlkit [required: >=0.10.1, installed: 0.12.3]
└── pylint-plugin-utils [required: >=0.8, installed: 0.8.2]
    └── pylint [required: >=1.7, installed: 3.0.3]
        ├── astroid [required: >=3.0.1,<=3.1.0-dev0, installed: 3.0.2]
        ├── dill [required: >=0.3.6, installed: 0.3.8]
        ├── isort [required: >=4.2.5,<6,!=5.13.0, installed: 5.13.2]
        ├── mccabe [required: >=0.6,<0.8, installed: 0.7.0]
        ├── platformdirs [required: >=2.2.0, installed: 3.11.0]
        └── tomlkit [required: >=0.10.1, installed: 0.12.3]
requests-mock==1.11.0
├── requests [required: >=2.3,<3, installed: 2.31.0]
│   ├── certifi [required: >=2017.4.17, installed: 2024.2.2]
│   ├── charset-normalizer [required: >=2,<4, installed: 3.3.2]
│   ├── idna [required: >=2.5,<4, installed: 3.6]
│   └── urllib3 [required: >=1.21.1,<3, installed: 2.0.7]
└── six [required: Any, installed: 1.16.0]
sentry-sdk==1.40.2
├── certifi [required: Any, installed: 2024.2.2]
└── urllib3 [required: >=1.26.11, installed: 2.0.7]
sib-api-v3-sdk==7.6.0
├── certifi [required: >=2017.4.17, installed: 2024.2.2]
├── python-dateutil [required: >=2.1, installed: 2.8.2]
│   └── six [required: >=1.5, installed: 1.16.0]
├── six [required: >=1.10, installed: 1.16.0]
└── urllib3 [required: >=1.23, installed: 2.0.7]
tomli==2.0.1
typing-extensions==4.9.0
wheel==0.42.0

```

closes #208

2024-02-20 13:33 UTC, alemangui requested changes

2024-02-20 13:49 UTC, alemangui commented
J'ai un souci avec psycopg2

```bash
• Installing psycopg2 (2.9.9): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
...
You may install a binary package by installing 'psycopg2-binary' from PyPI.
If you want to install psycopg2 from source, please install the packages
required for the build and try again.
  
For further information please check the 'doc/src/install.rst' file (also at
<https://www.psycopg.org/docs/install.html>).

...
Note: This error originates from the build backend, and is likely not a problem with poetry but with psycopg2 (2.9.9) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "psycopg2 (==2.9.9)"'.
```

Ça semble lié à https://github.com/openai/chatgpt-retrieval-plugin/issues/295. On pourrait tenter avec psycopg2-binary... pour l'instant je regarde si c'est qqchose lié à mon environnement.

2024-02-20 14:16 UTC, ddahan commented on pyproject.toml
> +django-extensions = "^3.2.3"
Nan car il y a en plus des devtools, des outils qui pourraient être utilisés en prod (champs additionnels, validators, etc.)

2024-02-20 14:25 UTC, alemangui approved these changes

2024-02-20 14:52 UTC, merged

2024-02-23 08:41 UTC, pletelli commented on .pre-commit-config.yaml
> +  - id: poetry-export
On n'a pas besoin de faire un `poetry-lock` au préalable comme mentionné dans https://python-poetry.org/docs/master/pre-commit-hooks/#poetry-export ?