Safe import 2
betagouv/complements-alimentaires pull request #241
Opened 2024-02-21 14:59 UTC by pletelli

remplace #211 
closes #174 

- [x] ajoute les mixins correspondant à nos différents champs déjà existants
- [x] modifie nos anciens champs en champs préfixés par  `siccrf_`
- [x] supprime des champs SICCRF très peu utilisés (cf [notebook d'analyse](https://github.com/betagouv/complements-alimentaires/blob/safe-import/notebooks/siccrf_fields_completion.ipynb))
- [x] la relation Part porte les 2 types de champs `siccrf_` et `CA_`
- [x] explicitation des relations entre ingrédients et substances
- [ ] ajout automatique du contenu des champs SICCRF peu utilisés et supprimés dans public_comments lors de l'import
- [x] ajoute les champs compl'alim utilisables par notre outil
- [x] property pour unifier les champs `CA_<field>` et les `siccrf_<field>` pour les property `name` et `is_obsolete` j'ajoute aussi une annotation au ModelManager pour pouvoir filtrer sur ces "champs proprietés" (cf https://stackoverflow.com/questions/53705551/emulate-filtering-by-property-in-django-using-property-and-queryset-annotation)
- [x] modifie l'importer CSV en conséquence

## Objectifs
* Il est maintenant possible de faire des scripts de transformation **automatique** des données qui vont remplir les champs `CA_*` à partir des champs `siccrf_*`
* Il est maintenant possible de faire des modifications **manuelles** des données dans l'interface d'admin : les champs modifiés sont enregistrés dans `CA_*` pour ne pas écraser les données sources `siccrf_*`
* Lors d'un nouvel import de csv siccrf, les `champs siccrf_*` sont écrasés

## Difficultés
L'admin django n'utilise pas les property comme champs du Form.

## Piste explorée mais pas poursuivie (à la place de 12a28fa9cb56fbf97b2579c78c8383a24d674134)
Transformation des relations entre ingrédients et substances en une table unique, dans models/substance.py, en utilisant le framework dj ContentType pour faire une [relation générique](https://docs.djangoproject.com/en/5.0/ref/contrib/contenttypes/#generic-relations)
mais cela semblait nous engoufrer dans une modèlisation assez peu flexible pour le futur.
```
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

class IngredientSubstanceRelation(WithCreationAndModificationDate, WithHistory):
    """
    Cette relation est une "generic-relation" django qui permet de faire une table unique pour tous les types d'ingrédients (plante, micro-organisme, ingredient)
    """
    ingredient_type = models.ForeignKey(ContentType, limit_choices_to={"model__in": ("Ingredient", "Plant", "Microorganism")}, on_delete=models.CASCADE)
    ingredient_id = models.PositiveIntegerField()
    ingredient = GenericForeignKey('ingredient_type', 'ingredient_id')
    substance = models.ForeignKey(Substance, on_delete=models.CASCADE)
    siccrf_is_related = models.BooleanField(default=False, verbose_name="substance associée à l'ingrédient (selon la base SICCRF)")
    CA_is_related = models.BooleanField(default=False, verbose_name="substance associée à l'ingrédient")
    
    class Meta:
        # pour le moment il faut forcer l'indexation des GenericForeignKey
        # cela changera à l'avenir https://code.djangoproject.com/ticket/23435
        indexes = [
            models.Index(fields=["ingredient_type", "ingredient_id"]),
        ]

```

## Remarques
Les différents commits font état de mes errements, j'ai laissé l'historique pour ne pas (trop) faire de push -f. Je peux nettoyer l'historique si demandé.
Au cours du dev, je me suis aussi rendu compte que je n'avais pas le bon formatter black (donc on voit des différence de config entre certains commits, mais pas entre le premier et le dernier).

2024-02-23 09:47 UTC, pletelli commented on data/models/mixins.py
> +    class Meta:
ajouter un commentaire explication. Merger les siccrf et CA default fields.

2024-02-23 09:49 UTC, pletelli commented on data/models/mixins.py
> +class WithCAComments(models.Model):
Ici maj avec GeneratedFields.

2024-02-23 10:01 UTC, pletelli commented on data/models/ingredient.py
> +    CA_is_related = models.BooleanField(null=True, default=None, verbose_name="substance associée à l'ingrédient")
En priorité : faire 2 champs ManyToMany
sinon il faut ajouter un generatedField (et filter soit au niveau du Manger, soit au niveau du serializer)

2024-02-26 11:34 UTC, ddahan commented
Un truc que je suis pas sûr d'avoir compris : pourquoi parfois on préfère garder des properties plutôt que des generated fields? Par exemple dans `WithCAComments`:

```python
    @property
    def public_comments(self):
        return self.CA_public_comments if self.CA_public_comments else self.siccrf_public_comments
```

2024-02-26 11:38 UTC, ddahan commented
Par rapport au besoin d’avoir `default=None` pour que le coalesce fonctionne sur les champs booléens, j’ai l’impression que la problématique est la même pour les `CharField` ou `TextField`. Par exemple :

```python
    siccrf_genre = models.TextField(verbose_name="genre de micro-organisme (selon la base SICCRF)")
    CA_genre = models.TextField(verbose_name="genre de micro-organisme")
    genre = models.GeneratedField(
        expression=Coalesce(F("CA_genre"), F("siccrf_genre")),
        output_field=models.TextField(verbose_name="genre de micro-organisme"),
        db_persist=True,
    )
```

Ici, `CA_genre` [n’est pas null](https://docs.djangoproject.com/en/5.0/ref/models/fields/#null) (c’est un empty string), donc c’est toujours `CA_genre` qui va être retourné alors qu’il na pas été sétté ? Parce que [la doc du coalesce 🐨](https://docs.djangoproject.com/en/5.0/ref/models/database-functions/#coalesce) dit bien “note that an empty string is not considered a null value”.

2024-02-26 11:43 UTC, ddahan commented on data/models/mixins.py
> +class WithCreationAndModificationDate(models.Model):
C'est du pinaillage, mais à l'époque j'avais eu un gros bug parce que `created` et `modified` n'avaient pas la même valeur et je m'en doutais pas du tout... Du coup j'avais changé pour : 

```python
class TimeStampable(models.Model):
    class Meta:
        abstract = True

    created = models.DateTimeField(editable=False)
    modified = models.DateTimeField(editable=False)

    def save(self, *args, **kwargs):
        """
        We don't use auto_now nor auto_now_add as this prevent to get the exact same
        value for created and modified fields.
        """
        now = timezone.now()
        if self._state.adding:
            self.created = now
        self.modified = now

        super().save(*args, **kwargs)
```

2024-02-26 11:53 UTC, ddahan commented
Et une question plutôt globale : là on utilise `Coalesce` pour déterminer quel champ on doit utiliser. Ca me semble être une bonne solution, à part peut-être dans les cas où la valeur `null` a une vraie signification fonctionnelle (ce qui semble pas être notre cas).

La question : est-ce qu'on a envisagé d'autre méthodes pour ça ? Par exemple [`case`](https://docs.djangoproject.com/en/5.0/ref/models/conditional-expressions/#case) ? Aucune idée de si ça peut être pertinent quelque part, c'est juste une question en l'air

2024-02-29 08:07 UTC, alemangui requested changes

2024-03-01 16:41 UTC, pletelli commented on data/factories/condition.py
> +    CA_name = factory.Faker("text", max_nb_chars=20)
Bonne remarque :) Je m'en suis apperçue en cours de dev, et j'ai ensuite oublié, je fais la modif ici dfa2947dd4d6179d955fdf62412c37fbf3a23284

2024-03-01 16:50 UTC, pletelli commented on api/serializers/plant.py
> +            "CA_family",
En effet ! Merci : 69be2fb4cdb8f7900b6b6e8119675f48a4bdf87a

2024-03-01 16:50 UTC, pletelli commented on api/serializers/plant.py
> +    CA_family = PlantFamilySerializer(read_only=True)
idem : 69be2fb4cdb8f7900b6b6e8119675f48a4bdf87a

2024-03-01 16:53 UTC, pletelli commented
> Et une question plutôt globale : là on utilise `Coalesce` pour déterminer quel champ on doit utiliser. Ca me semble être une bonne solution, à part peut-être dans les cas où la valeur `null` a une vraie signification fonctionnelle (ce qui semble pas être notre cas).
> 
> La question : est-ce qu'on a envisagé d'autre méthodes pour ça ? Par exemple [`case`](https://docs.djangoproject.com/en/5.0/ref/models/conditional-expressions/#case) ? Aucune idée de si ça peut être pertinent quelque part, c'est juste une question en l'air

Je n'ai pas vraiment envisagé d'autre méthode, en effet parce que la valeur `null` ou "" dans le cas des TextField n'a pas de signification fonctionnelle (pour l'instant).

2024-03-01 16:58 UTC, pletelli commented
> Par rapport au besoin d’avoir `default=None` pour que le coalesce fonctionne sur les champs booléens, j’ai l’impression que la problématique est la même pour les `CharField` ou `TextField`. Par exemple :
> 
> ```python
>     siccrf_genre = models.TextField(verbose_name="genre de micro-organisme (selon la base SICCRF)")
>     CA_genre = models.TextField(verbose_name="genre de micro-organisme")
>     genre = models.GeneratedField(
>         expression=Coalesce(F("CA_genre"), F("siccrf_genre")),
>         output_field=models.TextField(verbose_name="genre de micro-organisme"),
>         db_persist=True,
>     )
> ```
> 
> Ici, `CA_genre` [n’est pas null](https://docs.djangoproject.com/en/5.0/ref/models/fields/#null) (c’est un empty string), donc c’est toujours `CA_genre` qui va être retourné alors qu’il na pas été sétté ? Parce que [la doc du coalesce 🐨](https://docs.djangoproject.com/en/5.0/ref/models/database-functions/#coalesce) dit bien “note that an empty string is not considered a null value”.

Bien vu ! Je l'avais fait pour les autres `TextField` mais genre était passé à la trappe : a2600714ff2fe6b15b554b108dcde70eaa38d697

2024-03-01 17:04 UTC, pletelli commented on data/models/mixins.py
> +class WithCAComments(models.Model):
Fix ici 4c8c54292057083c13ee20c635b1a1757a85832a

2024-03-01 17:05 UTC, pletelli commented
> Un truc que je suis pas sûr d'avoir compris : pourquoi parfois on préfère garder des properties plutôt que des generated fields? Par exemple dans `WithCAComments`:
> 
> ```python
>     @property
>     def public_comments(self):
>         return self.CA_public_comments if self.CA_public_comments else self.siccrf_public_comments
> ```

On ne préfère pas, c'est un oubli : 4c8c54292057083c13ee20c635b1a1757a85832a

2024-03-04 09:47 UTC, pletelli commented on data/models/mixins.py
> +class WithCreationAndModificationDate(models.Model):
J'imagine un bug lié à un filtre sur la recherche d'égalité entre `self.created == self.modified` qui finalement remonte jamais aucun objet ?
Je comprends bien ton warning... mais j'ai l'impression que c'est un peu trop en prévision d'un usage qu'on n'a pas encore ?

2024-03-04 15:57 UTC, pletelli commented on data/models/ingredient.py
> +    CA_is_related = models.BooleanField(null=True, default=None, verbose_name="substance associée à l'ingrédient")
Le résultat de cette investigation se trouve ici : https://github.com/orgs/betagouv/projects/67?pane=issue&itemId=55225607
En gros, on ne peut pas faire de GeneratedField sur des champs qui héritent de RelatedField (ManytoManyField ou ForeignKey). 
Pas de doc django pour exprimer ça mais après recherche dans le code (et confirmation chatgpt) c'est mort, en tout cas en l'état actuel du code django.
Je ne comprends pas trop cette limitation parce que dans Psql c'est possible.


Donc pout les <Element>SubstanceRelation :
* on ne peut pas faire 2 champs ManyToMany qui seront ensuite Coalesce dans un champ GeneratedField.
* on peut garder la 

Pour la relation entre Plant et PlantFamily : une ForeignKey siccrf_family et une ca_family, il n'est pas possible de les coalesce dans un GeneratedField. Mais on peut :
* faire une table intermédiaire, avec deux champ siccrf_is_related, ca_is_related, et un generatedField is_related
* ou laisser tel quel (avec 2 champs dans la table Plant plutôt que dans la table intermédiaire) en ajoutant une property
~~~
    @property
    def family(self):
        family_pk = self.ca_family | self.siccrf_family
        try:
            return PlantFamily.objects.get(pk=self.siccrf_family)
        except PlantFamily.DoesNotExist:
            return None
~~~

2024-03-05 10:34 UTC, alemangui commented on data/models/ingredient.py
> +    CA_is_related = models.BooleanField(null=True, default=None, verbose_name="substance associée à l'ingrédient")
Merci pour cette super investigation ! Dommage cette limitation. 

Je dirais de rester au plus simple sachant que ce sont des champs voués à disparaître en fin d'année. Sauf erreur de ma part, le plus simple serait d'avoir les deux champs et d'utiliser une `@property` dans les deux cas non ?

2024-03-05 10:36 UTC, alemangui approved these changes

2024-03-05 10:48 UTC, merged