Refactoring 2
betagouv/complements-alimentaires pull request #266
Opened 2024-03-04 12:11 UTC by ddahan

Le but de cette PR est de continuer le travail de refactoring démarré sur une partie des fichiers du frontend.

**Refacto**
- UseFetch et await/async
- Utilisation de composants intermédiaires pour éviter les répétitions 
- Retrait de `onMounted`, à priori pas nécessaire dans les cas rencontrés
- Renommage pour éviter les ambiguités, et grouper les éléments alphabétiquement (ex : SearchResults -> ElementSearchResults)
- Remplacement de CSS par classes Tailwind (pas encore partout néanmoins)

**Autres**
- Setting VSCode permettant de voir dans l'onglet le dossier du fichier ouvert, pour avoir plus de clarté. Exemple d'utilité :
<img width="762" alt="Screenshot 2024-03-04 at 10 15 24" src="https://github.com/betagouv/complements-alimentaires/assets/1933516/70eac23c-d0e1-4293-b4b1-29c1a3b4f13d">
- Setting ESLint pour pouvoir continuer à travailler en cas de variable inutilisée (le warning apparait toujours très clairement dans la console, et une règle de pre-commit doit assurer de pas pouvoir pusher du code en warning)

### Questionnement / difficultés
- Souci de merge à vérifier sur [frontend/src/views/ProducerFormPage/CompositionStep.vue](https://github.com/betagouv/complements-alimentaires/compare/refacto2?expand=1#diff-a0ff01a14deeb44e0717b14c7d5eddb94f06d78238b6a1db53df4040f4028751) → ce fichier j’ai mal mergé ?
- Si les settings vous semblent moins bien qu'avant, on peut bien-sûr trouver autre chose
- A discuter : après avoir[ bien lu la doc](https://vuejs.org/guide/built-ins/suspense.html#suspense), l'utilisation de `Suspense` me semble pas appropriée dans 100% des cas. Son usage semble être davantage recommandé pour les pages qui vont fetch différentes données et  veulent pas afficher les résultats 1 par 1. Néanmoins, sa non-utilisation force à ne pas avoir de top level `await`, et donc wrapper l'appel à `useFetch` dans une autre méthode, ce qui peut alourdir la syntaxe. Au final, je ne suis toujours pas sûr de ce qui est le mieux pour nous. Exemple ci-dessous:

```js
// Sans <Suspense> qui wrappe le composant
const { data, error, execute } = useFetch(url, { immediate: false }).get().json()
const getMyItem = async () => {
  await execute()
  if (error.value) useToaster().addUnknownErrorMessage()
}
getMyItem() // pas de top-level-await => pas besoin de Suspense

// Avec <Suspense> qui wrappe le composant
const { data, error } = await useFetch(url).get().json() // top-level-await => besoin de Suspense
if (error.value) useToaster().addUnknownErrorMessage()
```

### Warnings
- Erreur sur la manière de créer une branche -> créé un faux historique de commits
- Il reste des `fetch()` dans ProducerForm (travail en cours) et dans `useRootStore()` (pas sûr du fonctionnement) (@alemangui -> peux-tu les mettre à jour toi à l'occasion ?
- `verifyResponse` → temporairement non réutilisé dans useFetch car on a prévu de refaire la gestion d'erreur entièrement dans un autre refacto (par exemple en ayant les erreurs venant du back, et peut-être en utilisant un [custom useFetch](https://vueuse.org/core/useFetch/#creating-a-custom-instance))

2024-03-05 09:44 UTC, pletelli commented on frontend/src/views/ProducerFormPage/CompositionStep.vue
> +const chosenIngredients = ref([])
`chosenElements` correspond mieux au wording adopté que `chosenIngredients` (Element inclue Ingredient, Microoerganism, Plantes, Substances)

2024-03-05 09:52 UTC, ddahan commented on frontend/src/views/ProducerFormPage/CompositionStep.vue
> +const chosenIngredients = ref([])
Justement à propos de ce fichier, je soupçonne que ce soit le seul où j'ai mal fait le merge manuel. J'attends le retour de @alemangui pour être sûr.

2024-03-05 09:53 UTC, pletelli commented on frontend/src/views/ProducerFormPage/CompositionStep.vue
> +  const { error, data } = await useFetch("/api/v1/substances/autocomplete/", { headers }).post(body).json()
ici aussi `elements`  semble plus approprié. C'est peut être arrivé au moment du merge.

2024-03-05 09:53 UTC, pletelli commented on frontend/src/views/ProducerFormPage/CompositionStep.vue
> +      title: "Error",
pb de merge : `Erreur` à favoriser au lieu de `Error`

2024-03-05 09:56 UTC, pletelli commented on pyproject.toml
> -django-extensions = "^3.2.3"
pourquoi installer django-extensions sur serveur ?

2024-03-05 11:38 UTC, alemangui requested changes

2024-03-05 11:38 UTC, alemangui commented on frontend/src/views/BlogHomePage.vue
> +            v-for="post in blogPosts?.results"
```suggestion
            v-for="post in blogPosts.results"
```
Ici on est sur de les avoir non ? Vu qu'on est à l'intérieur d'un `v-if="blogPosts.results.length > 0"`

2024-03-05 11:38 UTC, alemangui commented on frontend/src/views/BlogHomePage.vue
> +const { data: blogPosts, error, execute, isFetching } = useFetch(url, { immediate: false }).json()
Éventuellement le nom de la variable `blogPosts` pourrait être repensé car ça contient plus d'info dedans lié à la pagination, non seulement les articles. Je n'arrive pas à penser à quelque chose de plus descriptif par contre... `blogPostData` ? (genre pour les usages de `.results`, `.count`...)

2024-03-05 11:38 UTC, alemangui commented on frontend/src/views/BlogHomePage.vue
Ce refacto fixe le bug https://github.com/betagouv/complements-alimentaires/issues/267 non ? :tada:

2024-03-05 11:38 UTC, alemangui commented on frontend/src/views/BlogPostPage.vue
> +  <!-- TODO: replace with error management feature from backend -->
En vrai le plus simple serait de faire une redirection à notre page 404 (qui n'existait pas quand on a codé ces lignes je crois) si l'article n'est pas trouvé. Par ex : 

```javascript
await execute()
if (error is notFound) // pseudo-code, je ne connais pas la syntaxe pour avoir l'info de l'erreur
    router.replace({ name: "NotFound" })
```

2024-03-05 11:38 UTC, alemangui commented on frontend/src/views/ProducerFormPage/CompositionStep.vue
En effet le merge a fait perdre les modifs de la branche _composition-ui_ (merge commit ca31a78d2ff7a9f3ce1ce5cf8832b648a67562e4). 

J'ai bcp modifié ce fichier aussi dans la PR #257, une possibilité serait de le remettre tel qu'il est en staging car les refactos à ce niveau pourraient déjà ne pas être à jour avec le travail du step composition.

2024-03-05 11:38 UTC, alemangui commented on frontend/src/views/ElementPage/index.vue
Dommage que git n'a pas tilté que ceci est un rename de `frontend/src/views/ElementPage.vue`

Pour aider git, des fois c'est mieux de faire un premier commit juste avec les renamings et un second avec les changements dans les fichiers, comme ça on a un historique plus réel. 

On a le même souci pour `ElementSearchResultsPage/index.vue`

2024-03-05 11:40 UTC, alemangui commented on .vscode/settings.json
> +  "workbench.editor.labelFormat": "short",
:heart:

2024-03-05 13:29 UTC, ddahan commented on pyproject.toml
> -django-extensions = "^3.2.3"
Parce que c'est un package qui ajoute toutes sortes d'outils différents (pas que des dev tools), utilisables aussi en staging/prod. Typiquement les commandes additionnelles peuvent être fort utiles si on a accès à un shell sur ces environnements.

2024-03-05 13:33 UTC, ddahan commented on frontend/src/views/BlogHomePage.vue
> +            v-for="post in blogPosts?.results"
Tout à fait, merci !

2024-03-05 13:37 UTC, ddahan commented on frontend/src/views/BlogHomePage.vue
Nope j'ai pas encore fix le bug, parce que j'ai pas vu de manière évidente d'où ça provenait, et je voulais me focus sur le refacto, d'où l'issue créée exprès.

2024-03-05 13:41 UTC, ddahan commented on frontend/src/views/BlogPostPage.vue
> +  <!-- TODO: replace with error management feature from backend -->
C'est une bonne idée, mais je pense que ça doit aller à un plus haut niveau pour ne gérer ça qu'une fois, plutôt que component par component.
Je l'ai volontairement pas traité ici en me disant qu'il y aura sûrement une meilleure manière de faire, par exemple avec ça : https://vueuse.org/core/useFetch/#creating-a-custom-instance ou un truc du genre (finalement une logique qui remplace un peu le `verifyResponse` actuel)

2024-03-05 13:42 UTC, ddahan commented on frontend/src/views/ElementPage/index.vue
Merci pour le tip :)

2024-03-05 13:54 UTC, ddahan commented on frontend/src/views/ProducerFormPage/CompositionStep.vue
Je m'en doutais :) Fixed.
J'ai retenu la leçon de partir depuis la branche staging pour créer une branche ^^

2024-03-05 14:35 UTC, alemangui commented on frontend/src/views/ProducerFormPage/CompositionStep.vue
Merci :raised_hands:  Après n'hésite pas à partir d'une branche existante, il faudra juste pas la squasher au moment du merge

2024-03-05 16:18 UTC, alemangui commented on frontend/src/views/BlogHomePage.vue
Au temps pour moi, j'ai cru l'avoir vu disparaître quand je faisais des tests

2024-03-06 13:09 UTC, alemangui commented on frontend/src/views/BlogPostPage.vue
> +  <!-- TODO: replace with error management feature from backend -->
Je vois, en effet ça serait cool d'avoir un comportement globale. Après il faudrait que les composants puissent gérer leur propre 404 si besoin. Çad, peut-être que le comportement par défaut sera aller dans la page `NotFound`, mais un composant voudra potentiellement afficher quelque chose de différent (un prompt de création, un redirection vers une liste, etc.).

En attendant, je ne vois pas trop du mal à faire la redirection ici, histoire d'éviter la régression.

2024-03-06 16:59 UTC, alemangui approved these changes

2024-03-07 09:09 UTC, ddahan commented on frontend/src/views/BlogPostPage.vue
> +  <!-- TODO: replace with error management feature from backend -->
Oui en effet. Ca permettra de pas oublier au moment du refacto aussi. C'est changé ! Pour info j'ai du changer la route du catch all sans trop comprendre en profondeur pourquoi. cf. https://stackoverflow.com/a/70343919/2255491

2024-03-07 09:11 UTC, merged