Premier jet sur les users / roles
betagouv/complements-alimentaires pull request #274
Opened 2024-03-07 15:07 UTC by ddahan

2024-03-11 13:28 UTC, alemangui commented on data/models/roles.py
> +    company = models.OneToOneField(
Je changerais celui-ci pour avoir un ManyToMany. Ou l'idée est d'en créer une instance par combinaison user-company ?

2024-03-11 14:58 UTC, ddahan commented on data/models/roles.py
> +    company = models.OneToOneField(
Ah ! Si un Supervisor peut avoir plusieurs companies, en effet un M2M me parait plus simple et naturel, que N instances sur `CompanySupervisor`. Il faudra juste bien que les éventuelles infos de la supervision soient dans le `through`. Je change ça, thx.

2024-03-11 16:16 UTC, ddahan commented on api/serializers/user.py
> +        role_serializer_mapping = {
Si vous ave une idée simple pour automatiser ça, avec plaisir ):

2024-03-11 16:20 UTC, ddahan commented on frontend/src/views/LoginPage.vue
Désolé je voulais pas l'ajouter dans cette PR, commit trop rapide 😅

2024-03-13 15:06 UTC, alemangui requested changes

2024-03-13 15:06 UTC, alemangui commented on icare/settings.py
> +DJANGO_APPS = [
C'est plus joli séparé comme ça, mais sauf erreur de ma part l'ordre des `INSTALLED_APPS` peut avoir des effets indésirables non ? :disappointed: , par ex : 
- Les apps plus hauts placés prennent précedence sur les autres pour les templates. Si on voulait surcharger un template il faudra qu'on puisse placer l'app plus haut. Avec ce refacto, les templates de Django prendront toujours priorité sur les nôtres.
> The order of [INSTALLED_APPS](https://docs.djangoproject.com/en/5.0/ref/settings/#std-setting-INSTALLED_APPS) is significant! For example, if you want to customize the Django admin, you might choose to override the standard admin/base_site.html template, from django.contrib.admin, with your own admin/base_site.html in myproject.polls. You must then make sure that your myproject.polls comes before django.contrib.admin in [INSTALLED_APPS](https://docs.djangoproject.com/en/5.0/ref/settings/#std-setting-INSTALLED_APPS)
- Pour les traductions (que potentiellement on pourrait utiliser vu que l'appli sera accessible dans toute l'Europe) on a le même souci de précédence 
- Pour les Django management commands

Est-ce qu'un division comme ça compliquerait la tâche de placer une app ayant besoin d'un ordre spécifique ? Ou est-ce du pinaillage ?

2024-03-17 10:34 UTC, ddahan commented on api/serializers/roles.py
> +        fields = BaseRoleSerializer.Meta.fields + ()
Oui car j'avais cru comprendre que ce qui est dans Meta n'est pas hérité malheureusement.

2024-03-17 10:43 UTC, ddahan commented on api/tests/test_user.py
> +        self.client.force_login(user=user)
Ah super merci, en effet je me demandais comment l'utiliser.

2024-03-17 13:08 UTC, ddahan commented on api/views/authentication.py
> +@method_decorator(csrf_exempt, name="dispatch")
Il ne devrait pas l'être en effet. J'ai essayé de gérer ça proprement mais je veux bien ton avis s'il y a une meilleure solution.

- Si j'ai bien compris, initialement, le CSRF token est set côté browser, quand la page Django est chargée via `vue-app.html` et sa ligne `window.CSRF_TOKEN = "{{ csrf_token }}";`

- Mon souci: après un login (en mode SPA via Vue), le CSRF token change côté back. Mais comme la page Django n'est pas refreshed, Vue n'est pas au courant du nouveau CSRF token. Du coup, à ce moment là, tout call à un endpoint POST va renvoyer une 403.

- Pour régler ça : 
  - je renvoie le nouveau token dans la Response du login: `return Response({"csrf_token": get_token(request)})`
  - puis je le set côté front : `window.CSRF_TOKEN = data.value.csrfToken`
  
  Malheureusement, de la manière dont on utilise notre utils de headers, c'est statique, et la mise à jour n'a pas d'effet :
  
```js
export const headers = {
  "X-CSRFToken": window.CSRF_TOKEN || "",
  "Content-Type": "application/json",
}
```

Pour que ça marche, je suis obligé de transformer l'objet en fonction : 

```js
export const headers = () => ({
  "X-CSRFToken": window.CSRF_TOKEN || "",
  "Content-Type": "application/json",
})
```

Et l'appeler différemment dans chaque fichier : ` {headers: headers()} `.

Ca me semble OK comme ça, mais tu si tu as une meilleure idée...

2024-03-17 13:11 UTC, ddahan commented on api/views/authentication.py
> +@method_decorator(csrf_exempt, name="dispatch")
By the way, à discuter ailleurs, mais je pense qu'à terme ce qui fait sens c'est d'unifier toutes les infos de l'utilisateur dans la session (y compris ce qu'on récupère aujourd'hui avec un endpoint dans `loggedUser`).

2024-03-17 13:15 UTC, ddahan commented on data/factories/user.py
> +    return "user_" + make_random_str(size=10, chars=string.ascii_letters)
Cf. ma réponse sur ton autre commentaire sur data/models/user.py

2024-03-17 13:18 UTC, ddahan commented on data/models/user.py
> +from django.contrib.auth.validators import ASCIIUsernameValidator
Alors justement, en lisant SimpleIsBetter (cf. ci-dessous), je m'étais dit que c'était mieux d'être restrictif et empêcher les accents dans les username. Mais si tu penses l'inverse, pas de souci je change.

<img width="948" alt="image" src="https://github.com/betagouv/complements-alimentaires/assets/1933516/c02c8811-f6aa-43ed-bf60-01afa87c54ce">

2024-03-17 13:27 UTC, ddahan commented on data/models/user.py
> +
Alors pour essayer de faire court : 
- Sur SimpleIsBetter, ils expliquent que c'est pas possible et qu'on est obligés de passer par `AbstractBaseUser`
- Ce que toi et moi on comprenait pas, et donc on a essayé de ne pas le faire...
- Jusqu'au moment où j'ai rencontré potentiellement une des raisons dont ils parlaient : impossible de faire fonctionner `objects = UserManager.from_queryset(UserQuerySet)()` de cette manière. 

L'un dans l'autre, je pense qu'on est gagnants de l'avoir sorti car on a tout au même endroit, plus de contrôle, et on voit bien ce qu'il se passe dans le même fichier. Je trouve que les modèles User pré-faits de Django apportent plus de confusion que d'aide in fine.

2024-03-17 13:28 UTC, ddahan commented on data/models/company.py
> +    siret = models.CharField(
Yep, c'était plutôt des champs "bidon" pour avoir quelque chose. Je te propose de changer ça au moment où on fera les "vrais" specs complètes des formulaires.

2024-03-17 13:31 UTC, ddahan commented on frontend/src/views/LoginPage.vue
> +  if (error.value) {
Alors, j'attends sagement qu'on valide [cette PR](https://github.com/betagouv/complements-alimentaires/pull/287) qui devrait débloquer la situation pour valider ça proprement :) :)

2024-03-17 13:35 UTC, ddahan commented on icare/settings.py
> +DJANGO_APPS = [
Intéressant, je pensais que l'ordre avait une importance que pour les middlewares. J'avais pas pensé au cas des templates :) Tu préfères revert, ou garder cette séparation jusqu'à ce que le souci de l'ordre se pose ?

2024-03-17 14:54 UTC, ddahan commented
_Nouveau le 17/03_ https://github.com/betagouv/complements-alimentaires/pull/274/commits/c3d758703ea8f99c179e80c103bbc0d0171525dc
- Mise à jour du template de connexion pour correspondre au maximum au [standard DSFR](https://www.systeme-de-design.gouv.fr/elements-d-interface/modeles/page-de-connexion/)

<img width="1190" alt="image" src="https://github.com/betagouv/complements-alimentaires/assets/1933516/2f7abc89-4650-4b38-abe4-477b8c3ffe11">

2024-03-17 15:09 UTC, ddahan commented
@alemangui 

Dans les [reco du DSFR]() je lis :

> Bonne pratiques
> Privilégier la demande d’adresse email plutôt qu’un identifiant pour la connexion avec identifiant. Les utilisateurs se rappelle plus facilement de leur email qu’un identifiant unique.

Ça me fait me questionner sur notre choix d'utiliser un identifiant.
Bien que je me rappelle du cas où la personne n'a plus accès à son adresse e-mail, et a oublié son mot de passe.
Mais la personne peut aussi bien oublier son identifiant, et ne plus pouvoir le récupérer si elle n'a plus accès à ses mails.

Qu'en penses-tu ?

2024-03-18 12:07 UTC, ddahan commented
_Nouveau le 18/03_  https://github.com/betagouv/complements-alimentaires/pull/274/commits/2727f20e1420c802a12526d4d61fe784acd27f6b

Closes https://github.com/betagouv/complements-alimentaires/issues/230

2024-03-18 14:57 UTC, ddahan commented
_Nouveau le 18/03_ (cf 4 derniers commits)
- Ajout du support minimal responsive
- Clean code avec des tools and wrappers

2024-03-19 06:31 UTC, alemangui commented on data/models/user.py
> +from django.contrib.auth.validators import ASCIIUsernameValidator
Je vois, perso je garderai le UnicodeUsernameValidator car sur les autres SE plusieurs personnes ajoutent des accents sur leurs usernames

2024-03-19 06:38 UTC, alemangui commented on data/models/user.py
> +
Ça marche, je suis curieux de ce comportement avec le UserManager pour ma culture personnelle. Ce n'est pas clair dans ma tête pourquoi ça bloque. Laissons le code comme dans la PR et puis si tu peux me montrer ça serait top.

2024-03-19 06:48 UTC, alemangui approved these changes

2024-03-19 08:29 UTC, merged

2024-03-19 09:20 UTC, pletelli commented on data/models/user.py
> +
Curieuse aussi de ce point !