Affichage des erreurs créés par le back-end
betagouv/complements-alimentaires pull request #287
Opened 2024-03-17 09:46 UTC by ddahan

### Comment ça fonctionne ?
- Le fonctionnement n'est pas trivial, et nécessite de comprendre au minimum comment fonctionne la gestion des Exceptions côté DRF. C'est pourquoi [une doc](https://github.com/betagouv/complements-alimentaires/blob/243ac020d6702040ca099a2c68f0450a7609ee19/api/doc.md) a été écrite pour comprendre comment fonctionne et comment utiliser ce mécanisme.

### Gains attendus
- Evidemment, récupérer les erreurs fournies par le back-end (ce qui est indispensable)
- Avoir une gestion des erreurs centralisées, pour ne plus devoir se poser la question dans chaque component front.

### Exemples illustrés

```py
class SubscribeNewsletter(APIView):
    def post(self, request):
        raise EmailAlreadyExists
```

#### Erreur de type "field"

```py
class EmailAlreadyExists(ProjectAPIException):
    default_detail = "L'adresse e-mail renseignée existe déjà."
    display = "field"
    field_name = "email"
```
<img width="574" alt="image" src="https://github.com/betagouv/complements-alimentaires/assets/1933516/fe22476f-0b13-4cf7-9619-a9d08cc588ba">

#### Erreur de type "non_field"

```py
class EmailAlreadyExists(ProjectAPIException):
    default_detail = "L'adresse e-mail renseignée existe déjà."
    display = "non_field"
```

<img width="580" alt="image" src="https://github.com/betagouv/complements-alimentaires/assets/1933516/3df5e06a-2c5c-464d-86c1-28900f80ca8b">

#### Erreur de type "global"

```py
class EmailAlreadyExists(ProjectAPIException):
    default_detail = "L'adresse e-mail renseignée existe déjà."
    display = "global"
```

<img width="877" alt="image" src="https://github.com/betagouv/complements-alimentaires/assets/1933516/a186b7af-f2ef-4ad1-af67-b2c123ecc1a6">

### Todo potentielles restantes
- Appliquer aux endpoints existants et "Battle tester" le mécanisme -> c'est en le confrontant au besoin qu'on verra s'il faut corriger des choses
- Né gère pas les erreurs multiples pour le moment (serait problématique sur des gros formulaires)

closes https://github.com/betagouv/complements-alimentaires/issues/213

2024-03-18 15:38 UTC, ddahan commented
À noter qu'il va falloir aussi consolider la manière dont un serializer DRF écrit ses erreurs (dans `serializer.errors`) et notre système.

2024-03-19 16:39 UTC, ddahan commented
À voir si on voudrait faire un mécanisme similaire pour les success response, pour avoir une symétrie dans la gestion des messages.

2024-03-20 07:24 UTC, alemangui requested changes

2024-03-20 07:24 UTC, alemangui commented on api/exception_handling.py
> +        log_level: int | None = logging.INFO,
Juste pour être sur d'avoir bien compris, par défaut toutes les exceptions sont logées avec un level `INFO` c'est bien ça ? Si on explicite `ErrorTrucMouche(log_level=None)` le log ne sera pas effectué ?

2024-03-20 07:24 UTC, alemangui commented on api/views/newsletter.py
> +            raise ProjectAPIException(global_error="Une erreur inconnue avec l'API SendInBlue a eu lieu.")
Je ne mettrai pas l'info sur notre fournisseur SMTP sur la réponse user, c'est trop technique. Peut-être quelque chose plus générique comme 
```suggestion
            raise ProjectAPIException(global_error="Une erreur inconnue a eu lieu lors de votre inscription à la newsletter, veuillez réessayer plus tard")
```

2024-03-20 07:24 UTC, alemangui commented on api/views/report_issue.py
> +        except ValidationError:  # NOTE: should not actually happen with the front-end validation
Pour le commentaire, en effet la validation front-end devrait bloquer ce cas, mais le backend ne doit pas faire confiance au front. Déjà car il pourrait avoir un bug, car le front peut jouer des requêtes modifiées, et parce que l'API sera sûrement ouverte aux pros dans le moyen terme.

2024-03-20 07:24 UTC, alemangui commented on api/views/search.py
> +            raise ProjectAPIException(global_error=f"La limite de pagination excède {self.max_pagination_limit}")
Je pense que ce message d'erreur est trop technique pour l'utilisateur. Eux ils ne pourront rien faire si côte front on a un bug lié à la limite de la pagination. Je suis pour avoir ce message dans le corps de l'erreur (et potentiellement sur la partie qui sera logée) mais pas trop pour la partie affichée à l'user. 

Par ex, est-ce qu'un param supplémentaire `techincal_info` serait utile dans ce cas ? 

```python
raise ProjectAPIException(technical_info=f"La limite de pagination excède {self.max_pagination_limit}", global_error="Nous avons rencontré une erreur sur la pagination, veuillez réessayer plus tard")
```
Et côté log on aurait les deux choses. Ça nous servirait pour éventuellement ajouter des infos pertinentes pour le debug (username par ex, etc)

2024-03-20 07:24 UTC, alemangui commented on data/exceptions.py
Je trouverais ce fichier mieux placé côté `api`, sous `api/exceptions` vu qu'ils sont exclusivement utilisé pour l'API

2024-03-20 07:24 UTC, alemangui commented on api/views/newsletter.py
> +                raise EmailAlreadyExists
Ce cas ne devrait pas lever une erreur côté user, juste un 200 (ou éventuellement un 204 car aucun changement n'est effectué). En gros l'action user est de s'inscrire à la newsletter, s'iel est déjà dedans, ce n'est pas une erreur mais un no-change.

2024-03-20 07:24 UTC, alemangui commented on frontend/src/stores/root.js
> +    // TODO: add error handling here, but weird bug with await and response
C'est quoi le bug de ce côté ? Une race condition ?

2024-03-20 07:24 UTC, alemangui commented on frontend/src/views/LoginPage.vue
> +const $externalResults = ref({})
Pour ma culture g, pourquoi le `$` au début de cette variable ?

2024-03-20 07:24 UTC, alemangui commented on frontend/src/components/FormWrapper.vue
> +defineProps({ externalResults: Object })
`externalResults` me semble un peu flou comme nom de variable, surtout qu'ici on gère des erreurs. 
- Est-ce qu'un renommage `errors` serait plus clair ? 
- Vu qu'on utilise seulement `externalResults.nonFieldErrors`, est-ce que ça vaut la peine de passer seulement ça comme prop ? et donc la nommer `nonFieldErrors` ?

2024-03-20 08:20 UTC, ddahan commented on api/views/newsletter.py
> +            raise ProjectAPIException(global_error="Une erreur inconnue avec l'API SendInBlue a eu lieu.")
Ok d'accord avec toi, mais alors dans ce cas si c'est "une erreur inconnue" je suppose c'est pas nécessaire de rajouter "lors de votre inscription à la newsletter" (parce que la personne le sait) et rester sur l'erreur serveur de base sans en créer une nouvelle.

2024-03-20 08:22 UTC, ddahan commented on api/views/report_issue.py
> +        except ValidationError:  # NOTE: should not actually happen with the front-end validation
Oui bien sûr, l'idée n'est pas vraiment de faire confiance à la validation front-end, mais de ne pas s'embêter à faire une belle erreur si jamais on est face à un hacker qui bypass la validation front :)
Dans l'idée, je pense qu'il faut qu'une forte validation back soit ajoutée à celle du front, seulement s'il y a un risque derrière (écriture ou autre).

2024-03-20 08:24 UTC, ddahan commented on api/views/search.py
> +            raise ProjectAPIException(global_error=f"La limite de pagination excède {self.max_pagination_limit}")
Ah my bad, j'ai cru que c'était une erreur envoyée au user mais en fait non.
Dans ce cas, en laissant simplement ce qu'il y avait, ça enverra "une erreur inconnue est survenue", parce que dans le custom exception handler, ça rentre dans le cas des erreurs qu'on veut pas catcher

2024-03-20 08:24 UTC, ddahan commented on data/exceptions.py
En effet

2024-03-20 08:26 UTC, ddahan commented on api/views/newsletter.py
> +                raise EmailAlreadyExists
D'accord

2024-03-20 08:27 UTC, ddahan commented on frontend/src/stores/root.js
> +    // TODO: add error handling here, but weird bug with await and response
Une infinite loop. Il faut que j'investigue davantage quand j'ai le temps. L'async de JS n'est pas toujours 100% clair pour moi :D

2024-03-20 08:29 UTC, ddahan commented on frontend/src/views/LoginPage.vue
> +const $externalResults = ref({})
Je pense que ça n'a pas d'impact parce que c'est moi qui le définit, et que c'est une convention voulue de Vuelidate, j'ai repris ce qu'ils utilisaient ici : https://vuelidate-next.netlify.app/advanced_usage.html#providing-external-validations-server-side-validation

2024-03-20 10:29 UTC, ddahan commented
Au passage je me permets de modifier les `JSONResponse` que je vois en `Response` de DRF pour plus de consistence, et après avoir lu ça :

<img width="594" alt="image" src="https://github.com/betagouv/complements-alimentaires/assets/1933516/388d87a9-f23f-49ee-9894-e81d78f6b6c0">

Si vous pensez que je ne devrais pas, dites moi :)

2024-03-20 10:38 UTC, ddahan commented on api/utils/responses.py
Cleaning que j'avais oublié. Au passage je me permets de modifier les `JSONResponse` que je vois en `Response` de DRF pour plus de consistence, et après avoir lu ça (cf. ci-dessous) :
(Si vous pensez que je ne devrais pas, dites moi)

<img width="594" alt="image" src="https://github.com/betagouv/complements-alimentaires/assets/1933516/388d87a9-f23f-49ee-9894-e81d78f6b6c0">

2024-03-20 10:38 UTC, ddahan commented on api/utils/responses.py
Ce fichier devient quasiment inutile du coup ^^

2024-03-20 17:11 UTC, ddahan commented on api/exception_handling.py
> +    This is the base Exception used to create any DRF error. It is used in two ways:
Arf c'est possible...trop l'habitude des commentaires en anglais j'ai du en mettre pas mal par réflexe :/

2024-03-21 10:04 UTC, alemangui commented on api/views/search.py
> +            raise ProjectAPIException(global_error=f"La limite de pagination excède {self.max_pagination_limit}")
Normalement c'est n'est pas un 500, Sentry catch les trucs non-handled côté back (sinon on serait plein de logs des bad requests), pour les autres ce serait ELK pour les consulter. D'où l’intérêt éventuel d'ajouter des infos debug.

On peut le faire dans un deuxième temps par contre. J'ajouterai un issue priorité basse.

2024-03-21 10:08 UTC, alemangui commented on frontend/src/components/FormWrapper.vue
> +defineProps({ externalResults: Object })
Ah oui je n'avais pas vu que vuelidate utilise `externalResults` aussi. Gardons-le pour l'instant, on pourra toujours renommer si besoin.

2024-03-21 10:11 UTC, alemangui requested changes

2024-03-21 10:11 UTC, alemangui commented on api/tests/test_search.py
> +        self.assertEqual(response.status_code, status.HTTP_500_INTERNAL_SERVER_ERROR)
Pas compris pourquoi un 500? C'est bien une requête mal faite non? un 400 serait plus adapté.

2024-03-21 11:01 UTC, alemangui approved these changes

2024-03-21 11:03 UTC, pletelli approved these changes

2024-03-21 11:51 UTC, merged