Utilisation des unités définies dans la table SICCRF REF_ICA_UNITE pour les Substances
betagouv/complements-alimentaires pull request #297
Opened 2024-03-19 11:36 UTC by pletelli

- [ ] création d'un modèle SubstanceUnit 
On stocke cette donnée en base au lieu d'un Enum dans Substance contrairement à la discussion que j'avais entammée avec toi @alemangui notamment car ces données peuvent être amenée à changer et dans ce cas il sera pas mal de laisser la main aux users avec le rôle d'instruction pour le faire + normalisation (cf cet [article](https://web.archive.org/web/20180324095351/http://komlenic.com/244/8-reasons-why-mysqls-enum-data-type-is-evil/), et cette [discussion](https://softwareengineering.stackexchange.com/questions/305148/why-would-you-store-an-enum-in-db) )

2024-03-20 07:27 UTC, alemangui commented
Bien vu pour les bugs dans la table substance ! :raised_hands:

2024-03-20 16:47 UTC, ddahan commented on data/models/substance.py
> +        default=None,
Plutôt `blank=True` que `default=None` ?

2024-03-20 16:48 UTC, ddahan approved these changes

2024-03-20 17:22 UTC, pletelli commented on data/models/substance.py
> +        default=None,
Ce serait mieux en effet.
Mais j'ai mis un default à None pour que la migration passe alors que :
* l'unit n'est pas déjà set
* je ne peux pas mettre un default à "mg" par exemple car je ne sais pas avant de l'importer quel sera l'id de "mg" (comme mg vient de la base SICCRF et qu'il faut que j'en conserve son id pour que les unités des substances restent les bonnes)

Je suis preneuse d'une autre idée si jamais tu en as une pour gérer ça.

2024-03-21 10:28 UTC, alemangui requested changes

2024-03-21 10:28 UTC, alemangui commented on frontend/src/views/ProducerFormPage/ProductStep.vue
> +              :options="units?.map((unit) => ({ text: unit.name, value: unit.name }))"
Sauf erreur de ma part si le `text` et `value` sont les mêmes, on peu simplement avoir une liste de strings :
```suggestion
              :options="units?.map((unit) => unit.name)"
```

2024-03-21 10:28 UTC, alemangui commented on frontend/src/stores/root.js
> +    console.log(units.value)
Petit oublie du console.log?

2024-03-21 10:28 UTC, alemangui commented on frontend/src/views/ProducerFormPage/SubstancesTable.vue
> +          <div class="sm:hidden ca-xs-title">Quantité par DJR (en {{ payload.substances[rowIndex].quantity }})</div>
Je pense qu'ici on veut la substance.unit ?
```suggestion
          <div class="sm:hidden ca-xs-title">Quantité par DJR (en {{ payload.substances[rowIndex].substance.unit }})</div>
```

![image](https://github.com/betagouv/complements-alimentaires/assets/1225929/cfb2f305-d7e5-4174-93e3-85cc7f0c5b35)

2024-03-21 10:28 UTC, alemangui commented on frontend/src/views/ProducerFormPage/index.vue
Pour après : à terme on pourra éventuellement paralléliser ces appels. Pas pour cette PR, seulement une possibilité en cas de soucis de perf.

2024-03-21 10:57 UTC, pletelli commented on frontend/src/views/ProducerFormPage/ProductStep.vue
> +              :options="units?.map((unit) => ({ text: unit.name, value: unit.name }))"
fixé ici 49fbf5356b2dcfe5d4ee57eae1891085a505dd05

2024-03-21 10:57 UTC, pletelli commented on frontend/src/views/ProducerFormPage/SubstancesTable.vue
> +          <div class="sm:hidden ca-xs-title">Quantité par DJR (en {{ payload.substances[rowIndex].quantity }})</div>
ici aussi 49fbf5356b2dcfe5d4ee57eae1891085a505dd05

2024-03-21 10:59 UTC, pletelli commented on frontend/src/views/ProducerFormPage/ProductStep.vue
> -const { populations, conditions, units } = storeToRefs(store)
@alemangui  suite à ta https://github.com/betagouv/complements-alimentaires/pull/303 j'ai lu la doc Pinia :D
Et donc unit n'a pas besoin d'être réactive ici.
Je n'ai pas l'impression que population et condition non plus d'ailleurs si ?

2024-03-21 11:41 UTC, alemangui commented on frontend/src/views/ProducerFormPage/ProductStep.vue
> -const { populations, conditions, units } = storeToRefs(store)
Ton commit https://github.com/betagouv/complements-alimentaires/pull/297/commits/6629ff0fd7ade982c16ea2af4fa1cf2951132c4a marche bien côté réactivité :+1:  car si tu accèdes à ces variables via le store (par ex `store.units?.map...` comme tu as fait) ça reste réactif car le store lui même est une variable réactive et par conséquent les propriétés internes le sont aussi. 

On perd la réactivité seulement si on fait un [deconstruct](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) directement à partir de `useRootStore()`, par ex : `const { units } = useRootStore()`, dans ce cas `units` ne changerait pas après la requête web, çad si jamais cette vue s'ouvre sans que la requête web ait fini, je pense que ces variables resteront à `null`.

Donc pour garder la réactivité on a ces deux choix équivalentes : 
:heavy_check_mark:  Accéder à la variable via le store
```javascript
const store = useRootStore()
store.units?.map...
```
:heavy_check_mark:  Deconstruct à partir de _storeToRefs_
```javascript
const store = useRootStore()
const { units } = storeToRefs(store)
units?.map...
```
:no_entry_sign:  Ce qui n'est pas OK (pour les `ref`s) est :
```javascript
const { units } = useRootStore()
units?.map...  // ne change pas après la requête
```

2024-03-21 11:43 UTC, alemangui approved these changes

2024-03-21 13:05 UTC, merged