Ajout des fixtures
betagouv/complements-alimentaires pull request #330
Opened 2024-03-26 08:42 UTC by ddahan

2024-03-28 11:16 UTC, ddahan commented
@pletelli Pour lancer la discussion du merge (ou pas) de nos features -> "Lien avec l'import de données ingrédients". Je me dis qu'avec le code + la démo, c'est plus pertinent d'en discuter maintenant, qu'avant la feature.

2024-04-02 06:54 UTC, alemangui requested changes

2024-04-02 06:54 UTC, alemangui commented on README.md
Je laisserais les deux apartés (celui avec le `createsuperuser` et celui avec les fixtures).

Sauf erreur de ma part, le hashing des mots de passe dépend de la variable d'environnement `SECRET_KEY`, qu'on ne devrait pas se partager (et encore mois dans des envs exposés comme démo, staging, etc). La fixture users peut être utile pour créer quelques objets user mais la création d'un superuser pourrait être quand même nécessaire.

2024-04-02 06:54 UTC, alemangui commented on fixtures/auth.Permission.yaml
Pourquoi est-ce qu'on a besoin de ce fichier? Les permissions de l'app `auth` ne sont pas ajoutées automatiquement avec les migrations?

2024-04-02 06:54 UTC, alemangui commented on fixtures/data.User.yaml
Je ne pense pas que les mots de passe fonctionnent en fixtures, sauf erreur de ma part le hashing dépend du `SECRET_KEY`, et ama on ne devrait pas en avoir le même.

À voir si ce fichier a du sens ou bien si on garde le step du `createsuperuser` après l'application des fixtures :thinking:

2024-04-02 07:19 UTC, ddahan commented on fixtures/data.User.yaml
Je pense pas parce que si c'était le cas, ça voudrait dire qu'on ne pourrait plus changer la `SECRET_KEY` dès qu'on est en production avec des utilisateurs, ce qui serait un problème en terme de sécurité.

Confirmé :

<img width="594" alt="image" src="https://github.com/betagouv/complements-alimentaires/assets/1933516/9b3fd587-46d3-433c-9a4b-c0b31aafc1c6">

2024-04-02 07:23 UTC, ddahan commented on fixtures/auth.Permission.yaml
Je pense qu'on pourrait le retirer, jusqu'à ce qu'on ajoute des permissions nous-mêmes, autres que celles créées par défaut par Django

2024-04-02 07:24 UTC, ddahan commented on README.md
Cf réponse sur `data.User.yaml`. On peut tout de même laisser une mention à `createsuperuser` dans le readme, ça mange pas de pain :)

2024-04-02 07:32 UTC, alemangui commented on fixtures/data.User.yaml
Au temps pour moi !

2024-04-02 07:33 UTC, alemangui commented on README.md
En effet erreur de ma part pour le SECRET !

2024-04-02 07:34 UTC, alemangui commented on fixtures/auth.Permission.yaml
Si je comprends bien ça voudrait dire enlever _("auth", "Permission")_ et _("auth", "Group")_ de la liste côte settings ? (jusqu'à ce qu'on les utilise ?)

2024-04-02 07:36 UTC, pletelli reviewed
Pour continuer la discussion, je suis sûre qu'il ne faut pas ajouter les Elements (en tout cas pas ceux importés des csv) en fixtures, notamment parce que ce sont des données non publiques.
Après je m'interroge sur le fait d'en ajouter des "fabriqués" en fixtures, puis dans le myloaddata de pouvoir choisir entre :
* import des éléments fake
* import des éléments des csv

2024-04-02 07:36 UTC, pletelli commented on README.md
Je laisserais la mention à createsuperuser dans le readme en effet :bread:

2024-04-02 07:46 UTC, ddahan commented on fixtures/auth.Permission.yaml
Je pense. Je vais essayer de les retirer et voir si tout fonctionne toujours bien.

2024-04-02 07:56 UTC, ddahan commented
> je suis sûre qu'il ne faut pas ajouter les Elements (en tout cas pas ceux importés des csv) en fixtures, notamment parce que ce sont des données non publiques. Après je m'interroge sur le fait d'en ajouter des "fabriqués" en fixtures, puis dans le myloaddata de pouvoir choisir entre :
> 
> * import des éléments fake
> * import des éléments des csv


-> import des éléments fake : ça peut être bien, mais si ça demande du taff à les créer, ça vaut pas le coup je pense. Sachant qu'on a `mydumpdata` exprès pour créer des fixtures automatiquement à partir de vrais données.

Autre Idée à cheval entre les 2 propositions : est-ce que les données des fixtures ne peuvent pas être un sous-ensemble du CSV qui ne comporte pas de risque de confidentialité ? (par exemple : 50 éléments réels, avec une colonne de données sensible anonymisée) ?

2024-04-02 08:04 UTC, ddahan commented on fixtures/auth.Permission.yaml
Ah, le soucis c'est que `myloadata` utilise un `flushdb` pour nettoyer la base : `Removes ALL DATA from the database, including data added during migrations.`

Donc sauf erreur, y'a 2 solutions : 
- Soit laisser tel quel (pose pas de souci à priori)
- Soit supprimer ces fichiers et utiliser `reset_db` au lieu de `flushdb` pour détruire et reconstruire la base, mais c'est plus long et plus lourd, et nécessite de fermer le serveur avant

2024-04-03 10:37 UTC, alemangui commented on fixtures/auth.Permission.yaml
En vrai on peut laisser tel qu'il est, pas besoin de tous ces changements pour un fichier de plus. Je pensais que c'était un truc plus light.

2024-04-03 10:38 UTC, alemangui approved these changes

2024-04-03 10:41 UTC, alemangui commented
@ddahan 
> Est-ce que par exemple on pourrait pas remplacer ces fichiers par des fixtures (suffisantes pour bosser en local, et non confidentielles) à la place ?
J'aime bien cette idée, je l'impression que ça rejoint ce que @pletelli dit « _Après je m'interroge sur le fait d'en ajouter des "fabriqués" en fixtures, puis dans le myloaddata de pouvoir choisir_ ».

2024-04-03 12:45 UTC, merged

2024-04-03 13:23 UTC, ddahan commented
> > Est-ce que par exemple on pourrait pas remplacer ces fichiers par des fixtures (suffisantes pour bosser en local, et non confidentielles) à la place ?
> 
> J'aime bien cette idée, je l'impression que ça rejoint ce que @pletelli dit « _Après je m'interroge sur le fait d'en ajouter des "fabriqués" en fixtures, puis dans le myloaddata de pouvoir choisir_ ».

Ah oui peut-être qu'on dit la même chose en fait.
En gros pour faire simple, si demain on a des fichiers de fixtures sur les éléments à la place des .csv versionnés, et que je peux faire `myloaddata` et avoir une base complète pour bosser, je suis happppyyy 👯‍♂️