Edit user
betagouv/complements-alimentaires pull request #356
Opened 2024-03-31 19:49 UTC by ddahan

2024-04-01 09:26 UTC, ddahan commented on api/serializers/roles.py
Astuce pour m'éviter des mappings et de la duplication de nom côté front

2024-04-01 09:33 UTC, ddahan commented on api/tests/test_user.py
> -        body = json.loads(response.content.decode())
J'utile `response.data` partout par cohérence, pour pas mixer les 2 façons

2024-04-01 09:41 UTC, ddahan commented on api/tests/utils.py
Classe très simple qui hérite de `APITestCase` et permet de définir des helpers, pour que les tests soient plus faciles/légers à écrire.

Entre autres : 
  - Au niveau de l'auth automatique : on peut passer un user existant (utile si on veut controler les caractéristiques de notre user), ou pas si on veut un user créé automatiquement (comme dans le décorateur)
  - L'url est construire automatiquement, juste en spécifiant le `viewname` en attribut de classe. Ca permet d'être léger et DRY.
----
	
- A priori, plus besoin du décorateur `authenticate` car j'ai injecté la même logique dans la méthode login. Ok pour toi @alemangui ?

- (Il faudra penser à "nettoyer" les autres fichiers de tests, pour rester uniforme)

2024-04-01 09:45 UTC, ddahan commented on frontend/src/components/AppHeader.vue
> +      <div class="flex justify-between whitespace-nowrap">
Sans ça, "tableau de bord" était écrit sur plusieurs lignes :/

2024-04-01 09:46 UTC, ddahan commented on frontend/src/components/AppHeader.vue
> +        onClick: () => logOut(),
Il y avait un bug avec les paramètres par défaut, mais là je suis plus sûr que ce soit nécessaire. Bref, ignorer.

2024-04-01 09:47 UTC, ddahan commented on frontend/src/components/PasswordDisplayToggle.vue
Utiliser 3 fois dans le code => sorti à part

2024-04-01 09:47 UTC, ddahan commented on frontend/src/components/PasswordRules.vue
Utiliser 2 fois dans le code => sorti à part

2024-04-01 09:50 UTC, ddahan commented on frontend/src/stores/root.js
> +  const setLoggedUser = (userData) => {
Séparation de la méthode, parce qu'après un `edit_user`, on veut pouvoir set le résultat sans fetch de nouveau les data (qui sont renvoyées aussi par `edit_user` pour éviter un call supplémentaire inutile)

2024-04-01 09:54 UTC, ddahan commented on frontend/src/views/DashboardPage/index.vue
> +      icon="ri-home-4-line"
Juste une maniaquerie car visuellement c'est recommandé de pas mélanger les icônes "solid" et les icones "outline"

2024-04-01 09:54 UTC, ddahan commented on frontend/src/views/DashboardPage/RoleBarBlock.vue
> +          <div class="shrink-0 fr-notice__title text-blue-france-sun-113">Bienvenue, {{ name }}</div>
On préfère peut être afficher le username ? J'ai pas trop d'avis

2024-04-01 09:55 UTC, ddahan commented on frontend/src/views/LoginPage.vue
> -        <DsfrInput v-model="state.username" label="Identifiant" labelVisible autofocus />
Marche pas comme je veux l'autofocus, tant pis, idée abandonnée

2024-04-01 09:56 UTC, ddahan commented on frontend/src/views/UserAccountPage/ChangePasswordBlock.vue
> +    // Logout is not really necessary but Django removes session id from front-end after a change password
C'était pas le comportement que je voulais par défaut, mais c'est pas très grave, ce genre d'action sera sûrement presque jamais utilisée dans les faits.

2024-04-01 09:59 UTC, ddahan commented on frontend/src/views/VerificationSentPage.vue
Comme on s'en sert 2 fois maintenant, plus facile d'avoir une page à part, vers laquelle on redirige après un signup, ou après une modification d'adresse e-mail.

2024-04-01 10:01 UTC, ddahan commented on frontend/src/views/UserAccountPage/EditPersonalInformationBlock.vue
> +    // TODO: we should repopulate form fields with reactive loggedUser, in case backend change data (e.g. normalization)
Par rapport à mon TODO, je veux bien un avis sur la manière de bien faire ça avec le loggerUser censé être réactif (même si ici on n'en a pas besoin directement car le back ne va pas changer nos données entrées).

2024-04-02 07:22 UTC, alemangui commented
@ddahan Merci pour les vidéos ! Ça rend la PR super claire :movie_camera:

2024-04-02 07:43 UTC, ddahan commented on frontend/src/icons.js
Ca rend le process d'ajout d'icône un tout petit peu moins chiant :D

2024-04-02 09:08 UTC, pletelli approved these changes
Je ne vois rien de bloquant au merge de mon côté, mais je n'ai pas les yeux les plus affutés :eyeglasses: 
Bravo pour cette gestion de compte !
Est-ce qu'on n'en profiterais pas pour supprimer les pages django de gestion de compte et éviter les doublons ?

2024-04-02 09:08 UTC, pletelli commented on frontend/src/views/DashboardPage/RoleBarBlock.vue
> +          <div class="shrink-0 fr-notice__title text-blue-france-sun-113">Bienvenue, {{ name }}</div>
Le username serait peut-etre un bon compromis "pas trop familier" ar rapport au firstname.

2024-04-02 09:22 UTC, alemangui commented on frontend/src/views/DashboardPage/RoleBarBlock.vue
> +          <div class="shrink-0 fr-notice__title text-blue-france-sun-113">Bienvenue, {{ name }}</div>
J'ai une préf pour le nom, tel qu'il est aujourd'hui. C'est plus personnel et les communications email d'habitude utilisent le nom plutôt que le username

2024-04-02 09:29 UTC, alemangui requested changes

2024-04-02 09:29 UTC, alemangui commented on frontend/src/views/UserAccountPage/EditPersonalInformationBlock.vue
> +        <DsfrInputGroup :error-message="firstErrorMsg(v$, 'username')">
Je ne mettrais pas la possibilité de changer l'username. À la limite je l'afficherais (genre en texte pur) quelque part, mais pas en mode éditable.

2024-04-02 09:29 UTC, alemangui commented on frontend/src/views/UserAccountPage/DeleteAccountBlock.vue
> +        Votre compte sera immédiatemment désactivé (vous ne pourrez plus vous connecter). Nous supprimerons ensuite dans
Je changerais le wording pour dire plus vaguement "Nous supprimerons vos données personnelles dans les meilleurs délais", pas de mention à la réglementation ni à la limite de temps pour pas se créer des soucis.

2024-04-02 09:29 UTC, alemangui commented on api/tests/utils.py
Je ne supprimerais pas `@authenticate` - d'autre PRs en cours l'utilisent. Puis je trouve utile de pouvoir identifier rapidement en haut de la fonction de test s'il s'agit d'un cas auth ou pas. 

Rien ne nous empêche d'avoir les deux - `mock` par exemple est utilisable en tant que decorateur et fonction.

2024-04-02 09:34 UTC, ddahan commented on frontend/src/router/index.js
> +import VerificationSentPage from "@/views//VerificationSentPage"
Oopsy, bravo les yeux de lynx. La vraie question c'est "pourquoi ça marchait comme ça ?" 😅

2024-04-02 09:36 UTC, ddahan commented on frontend/src/views/UserAccountPage/EditPersonalInformationBlock.vue
> +        <DsfrInputGroup :error-message="firstErrorMsg(v$, 'username')">
Pour quelle raison ?
(sachant que le username doit pas être utilisé comme attribut de lookup ou d'identification unique, puisqu'on a un id exprès pour ça)

2024-04-02 09:44 UTC, ddahan commented on frontend/src/views/UserAccountPage/DeleteAccountBlock.vue
> +        Votre compte sera immédiatemment désactivé (vous ne pourrez plus vous connecter). Nous supprimerons ensuite dans
Ok je le laisse au moins pour le moment pour pas casser les PR en cours.
Par contre à terme je pense que ça fera doublon, parce que `self.login()` fait exactement la même chose

2024-04-02 09:52 UTC, ddahan commented on api/tests/utils.py
- Ok je l'ai remis au moins pour le moment pour pas casser les PR en cours.
- `self.login()` fait exactement la même chose (avec plus de possibilités comme passer un user, ou faire le login à endroit spécifique dans le test) -> du coup à terme je vois pas trop d'intérêt de le garder, sauf cas contraire ?

2024-04-03 15:06 UTC, alemangui commented on frontend/src/views/UserAccountPage/EditPersonalInformationBlock.vue
> +        <DsfrInputGroup :error-message="firstErrorMsg(v$, 'username')">
Ça semble un peu bête mais ça peut arriver que les personnes le changent sans faire exprès ou le confondent avec un autre champ, oubliant après le username dont ils ont besoin pour accéder.

Cela dit, il y a aussi des raisons légitimes pour changer le username :thinking: Je te laisse décider, je n'ai pas d'avis fort d'un côte ou d'un autre. On pourra toujours changer la fonctionnalité par la suite.

2024-04-03 15:55 UTC, alemangui requested changes

2024-04-03 15:55 UTC, alemangui commented on api/tests/test_user.py
> +        email = "eren@mikasa.com"
Pour les adresses email et les domaines fake on peut utiliser _example.com_, qui fait partie des [domaines réservés](https://en.wikipedia.org/wiki/Example.com) par la IANA pour faire des tests ou servir de placeholders.
```suggestion
        email = "eren@example.com"
```

2024-04-03 15:55 UTC, alemangui commented on api/tests/test_user.py
> +        self.user_data = dict(last_name="Cook", first_name="Tim", email="tim.cook@exemple.com", username="tcook")
```suggestion
        self.user_data = dict(last_name="Cook", first_name="Tim", email="tim.cook@example.com", username="tcook")
```

2024-04-03 15:55 UTC, alemangui commented on api/tests/test_user.py
> +        self.assertTrue(response.data["non_field_errors"])  # Django default behaviour
Peut-être franciser les comments ? (il n'y en a pas bcp dans ce fichier, mais ça permettrait de ne pas faire grandir le nombre de comments en anglais)

2024-04-03 15:55 UTC, alemangui commented on api/tests/test_user.py
> +        new_last_name = "Cookie"
Tim Cookie :cookie: Je l'appellerai désormais comme ça.

2024-04-03 15:55 UTC, alemangui commented on api/tests/test_user.py
> +        new_email = "tim.cookie@exemple.com"
```suggestion
        new_email = "tim.cookie@example.com"
```

2024-04-03 15:55 UTC, alemangui commented on api/tests/test_user.py
> +        existing_email = "sundar.pichai@exemple.com"
```suggestion
        existing_email = "sundar.pichai@example.com"
```

2024-04-03 15:55 UTC, alemangui commented on api/tests/test_user.py
> +        # NOTE: first_name and last_name are not mandatory at back-end level (should they?)
Bonne question. Laissons le en mode pas obligatoire pour l'instant et voyons après (ref obligatoire à [falsehoods programmers believe about names](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/) point 40 ^^)

2024-04-03 15:55 UTC, alemangui commented on api/urls.py
> +    path("edit-user/", views.EditUserView.as_view(), name="edit_user"),
Pourquoi pas l'avoir en mode REST genre 
- `POST user/<id>` pour l'édition
- `DELETE user/<id>` pour la suppression ?
(Par contre je laisserais bien `change-password` en mode non-rest car c'est un autre flow)

2024-04-03 15:55 UTC, alemangui commented on api/views/user.py
> +
Éventuellement une autre façon de faire serait d'avoir une seule vue qui hérite de `[RetrieveDestroyAPIView](https://www.django-rest-framework.org/api-guide/generic-views/#retrievedestroyapiview)`, par ex :

```python
# Alerte pseudocode, pas trop faire confiance
class UserRetrieveDestroyView(RetrieveDestroyView):
    permission_classes = [permissions.IsAuthenticated] # À mettre une permission genre isLoggedUser
    serializer_class = EditUserSerializer

    def perform_update(self, serializer):
        previous_email = serializer.instance.email
        new_email = serializer.validated_data.get("email", previous_email)
        update = super().perform_update(serializer) # l'exception sera levée côté serializer de toute façon
        if previous_email != new_email:
            # _send_verification_mail(self.request, self.request.user) Petit comment sur cette ligne ci-dessous
            _send_verification_mail(serializer.instance)
        return update

    def perform_delete(self, serializer):
        """NOTE: this does not delete anything actually"""
        user = request.user
        user.deactivate()
        send_mail(
            subject="Nouvelle demande de suppression de compte",
            message=f"{user.name} (id: {user.id}) a demandé la suppression de son compte.",
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[settings.CONTACT_EMAIL],
        )
        # tout seul ça répondra avec un 204 No content
```

## Côté URLs

Ça fait qu'on peut ajouter ça en mode REST :
```python
# urls.py

path("user/<int:pk>", views.UserRetrieveDestroyView.as_view(), name="edit_delete_user"),
```
Et on aura automatiquement les POST et DELETE pour ce path.

## Petite note additionnelle

Je n'avais pas remarqué que `_send_verification_mail(self.request, self.request.user)` prend la requête pour former l'URL des liens. Ce serait mieux d'utiliser la variable d'env `HOSTNAME` pour cela, déjà pour ne pas dépendre de la requête, pour pouvoir overrider cette env var dans des tests etc, et aussi car l'appli peut être servi depuis plus d'un URL (ou au moins depuis un IP).

2024-04-03 15:55 UTC, alemangui commented on data/models/user.py
> -    @cached_property
Tu auras p-e un conflit car je les ai enlevé aussi, mais bon c'est facile à régler

2024-04-03 15:55 UTC, alemangui commented on frontend/src/views/UserAccountPage/EditPersonalInformationBlock.vue
> +    // TODO: we should repopulate form fields with reactive loggedUser, in case backend change data (e.g. normalization)
Ça ne s'update pas tout seul avec le state même avec le `storeToRefs` ?

2024-04-04 08:28 UTC, ddahan commented on frontend/src/views/UserAccountPage/EditPersonalInformationBlock.vue
> +        <DsfrInputGroup :error-message="firstErrorMsg(v$, 'username')">
J'ai pas d'avis fort non plus, et chatGPT non plus je crois (cf. ci-dessous).
Je propose de garder l'existant, pas parce que c'est mieux, mais juste parce que ça fait pas de rework à faire.

<img width="609" alt="image" src="https://github.com/betagouv/complements-alimentaires/assets/1933516/676b46a5-2d7f-46a6-9361-0bcdafe49eeb">

2024-04-04 08:33 UTC, ddahan commented on api/tests/test_user.py
> +        self.assertTrue(response.data["non_field_errors"])  # Django default behaviour
Oui. Je t'avoue que j'avais arrêté de m'en soucier quand j'ai vu qu'il y avait sûrement plus d'anglais que de français actuellement. Mais si on est sûr qu'on doit aller vers le français, alors oui il faudrait faire ça t'as raison.
J'vais fait une issue sur le sujet : https://github.com/betagouv/complements-alimentaires/issues/335
Ca me dérange pas de passer 1h à tout corriger le projet dans une autre PR.

2024-04-04 08:41 UTC, ddahan commented on api/urls.py
> +    path("edit-user/", views.EditUserView.as_view(), name="edit_user"),
Ouais j'y pensais, mais je croyais que t'étais pas trop chaud
Par contre je pense que si on le fait en mode REST, c'est à fond, genre :  
- `POST user/` pour le signup
- `PUT user/` pour l'édition (pas d'id à fournir car user loggé)
- `DELETE user/` pour la suppression (idem)
- `GET user/<id>` pour la récupéréation du loggerUser.

Puis : 
- `PUT user/change-password` (pour garder le namespace du user?) @alemangui

2024-04-04 10:48 UTC, ddahan commented on api/urls.py
> +    path("edit-user/", views.EditUserView.as_view(), name="edit_user"),
Très chaud pour l'avoir en mode REST (je trouve ça bien plus propre), j'ai fait les modifs ici : https://github.com/betagouv/complements-alimentaires/pull/356/commits/a463569790a57c5298dca1df67b09a717b4cf51c

J'ai été un chouille plus loin que ce que tu proposes en ajoutant le GET pour le loggedUser, et le POST pour le signup (le PUT étant pour l'édition). Ca nous fait donc 1 endpoint sur `user/` au lieu de 4, je trouve ça très clair à lire dans le code comme ça. Je suis pas fan de REST mais je dois avouer que ce cas est vraiment adapté :)

Je pense qu'à terme on pourrait aussi avoir comme url `user/change-password` au lieu de `change-password` quand il commencera à y avoir trop d'url (ou pas).

Concernant les vues génériques (et merci pour ton exemple !), je trouve que c'est une super possibilité de la part de DRF, mais qui peut aussi rendre le code plus complexe à écrire et à lire (c'est le même débat que FBV vs CBV en Django). Du coup je pense les utiliser quand le gain est vraiment évident. Là dans ce cas précis, je pense que ça vaut pas le coup car le code sans, me semble très simple à lire et à écrire. Mais j'avoue que je serais curieux d'avoir l'équivalent en mode générique pour comparer side by side.

2024-04-04 10:50 UTC, ddahan commented on api/views/user.py
> +
> Éventuellement une autre façon de faire

Répondu plus haut

> Petite note additionnelle

Très bon point l'appli qui peut être servi depuis plus d'un URL/IP 👏🏻 je vais changer ça !

2024-04-04 11:45 UTC, ddahan commented on api/views/user.py
> +
Fait sur ce dernier commit : https://github.com/betagouv/complements-alimentaires/pull/356/commits/8602c22afc3a4c511472893b273e795ea7f1be24.

Par contre ça m'a permis de découvrir un bug : https://github.com/betagouv/complements-alimentaires/issues/371 (qui pourrait aussi avoir lieu en prod)

2024-04-04 11:47 UTC, ddahan commented on frontend/src/views/UserAccountPage/EditPersonalInformationBlock.vue
> +    // TODO: we should repopulate form fields with reactive loggedUser, in case backend change data (e.g. normalization)
Non mais je suppose que le souci vient de moi qui sait mal l'utiliser.
Comme ça concerne pas ce cas précis, je propose d'en reparler plus tard.

2024-04-04 17:41 UTC, ddahan commented on api/permissions.py
> +        return isinstance(obj, get_user_model()) and request.user.is_authenticated and request.user == obj
- Je crois que tester juste `request.user` c'était déconseillé au cas le user est anonymous.
- Question : pourquoi tester `isinstance(obj, get_user_model())` sachant que ça sera toujours vrai si `request.user == obj`

2024-04-04 17:43 UTC, ddahan commented on api/serializers/user.py
> +    id = serializers.IntegerField(read_only=True)
Cette ligne m'a sauvé la vie, sinon il fallait override le `create` dans la view

2024-04-04 17:43 UTC, ddahan commented on api/tests/test_user.py
> +    viewname = "get_logged_user"
on repasse avec un nom style RPC pour faire comprendre que c'est plus dans la partie REST

2024-04-04 17:44 UTC, ddahan commented on api/tests/utils.py
> +        url = reverse(f"{self.namespace}:{self.viewname}", args=args, kwargs=kwargs)
Petit bug sur le passage des args/kwargs fix au passage

2024-04-04 17:45 UTC, ddahan commented on api/urls.py
> +    path("users/<int:pk>", views.UserUpdateDestroyView.as_view(), name="user_update_destroy"),
Selon là où tu regardes, certains REST-guys préfèrent `"user/<int:pk>"` (sans le s). Dis moi si tu veux changer.

2024-04-04 17:47 UTC, ddahan commented on api/views/user.py
> +    @transaction.atomic
Je sais comment faire encore mieux, je t'en reparlerai plus tard :)

2024-04-04 17:47 UTC, ddahan commented on frontend/src/views/UserAccountPage/DeleteAccountBlock.vue
> +  `/api/v1/users/${store.loggedUser.id}`,
pas le storeToRef, mais ça a l'air de marcher quand même comme voulu.

2024-04-04 17:54 UTC, ddahan commented on api/views/user.py
> +        raise MethodNotAllowed("Retrieve feature should not be used here")
Finalement raise l'erreur de DRF me semble plus propre, comme ça on a le même type d'erreur

2024-04-05 07:22 UTC, alemangui commented on api/permissions.py
> +        return isinstance(obj, get_user_model()) and request.user.is_authenticated and request.user == obj
Tu as raison, pas besoin du `isinstance`, my bad!

2024-04-05 07:24 UTC, alemangui commented on api/urls.py
> +    path("users/<int:pk>", views.UserUpdateDestroyView.as_view(), name="user_update_destroy"),
J'aime bien avec la `s`, ça me semble plus cohérent :+1:

2024-04-05 07:30 UTC, alemangui commented on api/urls.py
> +    path("get-logged-user/", views.LoggedUserView.as_view(), name="get_logged_user"),
@ddahan bien vu pour le casing :+1:  J'étais parti pour un _camelCase_ pour les URLs de l'API mais je pense qu'un _spinal-case_ est plus cohérent avec les URLs de l'app web et ça colle avec le RFC3986. On changera par la suite les endpoints `subscribeNewsletter`, `plantParts`, etc (dans une autre PR)

2024-04-05 07:30 UTC, alemangui approved these changes

2024-04-05 07:43 UTC, merged