[FIX] Problème de collisions de variables d'environnement
betagouv/complements-alimentaires pull request #372
Opened 2024-04-04 12:21 UTC by ddahan

Closes https://github.com/betagouv/complements-alimentaires/issues/371

### Note
- À merger à part, en mettant directement à jour les environnements clevercloud derrière, pour éviter d'oublier

2024-04-05 08:48 UTC, alemangui requested changes

2024-04-05 08:48 UTC, alemangui commented on config/settings.py
Pas besoin de prefixer les env-vars, si on met le param `overwrite` à True de django-environ ([doc](https://django-environ.readthedocs.io/en/latest/api.html#environ.Env.read_env)) les variables du fichier .env prennent priorité
```python
environ.Env.read_env(os.path.join(BASE_DIR, ".env"), overwrite=True)
```

2024-04-09 06:34 UTC, ddahan commented on config/settings.py
@alemangui  Je pense pas, ce paramètre va juste permettre si la variable d'environnement existe déjà au moment du `read_env`, de ne pas l'overwrite. Mais techniquement il n'y a rien qui peut empêcher n'importe quel autre programme de venir écraser les variables d'environnement d'unix à tout moment, en dehors de Django.

2024-04-09 07:08 UTC, alemangui commented on config/settings.py
Je l'ai testé et ça override bien les vars. Si le procès Django est lancé, dans le procès les env vars ne pourront pas être surchargées par un autre procès.

2024-04-09 07:13 UTC, ddahan commented on config/settings.py
Ah ? Qu'est ce qui l'empêche techniquement ? Je lis :

> Il n'y a pas de mécanisme direct fourni par Unix ou les systèmes similaires pour verrouiller ou rendre une variable d'environnement immuable après sa création. La mutabilité des variables d'environnement est une caractéristique conçue, permettant une flexibilité dans la configuration et l'exécution des programmes.

2024-04-09 07:21 UTC, alemangui commented on config/settings.py
Et puis rien n'empêche que si j'ai un logiciel de musique DJ il ne surcharge pas DJ_HOSTNAME. Il faut juste s'assurer que django-environ donne priorité à notre fichier.

2024-04-09 07:24 UTC, ddahan commented on config/settings.py
My 2 cents: je pense que :
- `overwrite=True` fonctionne que dans le cas où le process Django est bien le dernier lancé (ça devrait souvent être le cas mais n'assure rien en tant que tel)
- `overwrite=True` créé un risque en plus : si jamais un .env est commit par erreur, la prod est morte
- le prexifage est une bonne pratique connue et recommandée dans les 12 factors apps (pour le risque retiré + la meilleure lisibilité en listant toutes les var d'envs) - c'est pas une solution custom, c'est assez standard.
 - comme la PR est déjà faite, je vois pas trop les points négatifs  le faire, le seul travail restant étant de changer les vars sur clevercloud au moment du déploiement.
 
 
![image](https://github.com/betagouv/complements-alimentaires/assets/1933516/1649c972-150e-4374-aafb-9eebb52fd06a)


Je te laisse décider, ça vaut pas le coup de passer plus de temps à en discuter je pense.

2024-04-09 07:53 UTC, alemangui commented on config/settings.py
Le overwrite ne fonctionne pas seulement si Django es le dernier lancé. Par ex, si on lance Django, et par la suite on change les envvars, le procès Django aura les mêmes envvars qu'avant le changement.  Si un _.env_ est commité par erreur on a beaucoup plus de soucis que ça, car des secrets seraient compromis, ce qui normalement est impossible via le gitignore.

Ça me semble trop gros en termes de code, risque, et d’ajustement à faire côté serveur pour quelque chose qui peut se fixer avec un paramètre dans une ligne (par ex comme ça de tête on utilise aussi les envvars dans le procès de build npm, sur _vue.config.js_)

2024-04-22 13:57 UTC, closed without merging