Ajout/reprise d'une entreprise
betagouv/complements-alimentaires pull request #392
Opened 2024-04-11 13:26 UTC by ddahan

2024-04-11 14:54 UTC, ddahan commented on frontend/src/views/CompanyFormPage/index.vue
C'est le fichier le plus important de cette PR. Ça mérite une petite explication (à regarder après avoir vu la démo sur la page de la PR) : https://drive.google.com/file/d/1AKoyJenctHcB4a-QKICnRuO2wUs5ckhM/view?usp=sharing

2024-04-12 06:14 UTC, alemangui commented on data/factories/company.py
> +
Pas sur d'avoir compris, on va rajouter un SIRET automatiquement généré c'est ça ?

2024-04-12 06:26 UTC, alemangui commented
Très cool cette UI/UX :clap:

2024-04-12 08:02 UTC, alemangui requested changes

2024-04-12 08:02 UTC, alemangui commented on frontend/src/views/CompanyFormPage/Introduction.vue
> +  </DsfrAlert> -->
Plutôt qu'un texte sur l'écran on mettra un listener de `beforeunload` pour montrer une alerte dans le cas où la sauvegarde n'a pas été faite (à terme, pas tout de suite)

2024-04-15 09:16 UTC, ddahan commented on api/views/company.py
> +class CompanyRetrieveView(RetrieveAPIView):
Partager l'url ? c'est à dire ? J'ai ça pour l'instant
```
path("companies/", views.CompanyCreateView.as_view(), name="company_create"),
path("companies/<int:pk>", views.CompanyRetrieveView.as_view(), name="company_retrieve"),
```

2024-04-15 09:18 UTC, ddahan commented on data/factories/company.py
> +
J'expliquais l'intérêt du pattern dans lequel il y a une classe qui fait la même chose que la classe mère, parce qu'on pourrait dire "autant utiliser `CompanyFactory` si ça fait pareil".
D'expérience, ça permet de changer les défauts des factories sans casser les tests dans le futur.
(sujet pas très important)

2024-04-15 09:23 UTC, ddahan commented on frontend/src/stores/createCompany.js
Ahh piste intéressante, merci ! Si je peux me débarrasser de ce state je vais le faire. Je reviens vers toi si j'ai des questions.

2024-04-15 09:30 UTC, ddahan commented on data/models/company.py
> +        if not (self.siret or self.vat):
Thanks! Ca serait cool une petite app `django-gouv` avec tous ces utils réutilisables :D

2024-04-15 09:33 UTC, ddahan commented on api/permissions.py
> +class IsSupervisorOfThisCompany(permissions.BasePermission):
Je me suis posé la même question, le souci c'est que `CompanySupervisor` c'est exactement le nom de la classe du role en question. Donc si on écrit `IsCompanySupervisor`, ça sous-entend que ça renvoie `True` si on a ce rôle là. Or ici, on veut pas uniquement le rôle, mais le rôle appliquée à une company spécifique. D'où mon nom un peu "bizarre" pour insister dessus :/

2024-04-15 09:39 UTC, ddahan commented on data/models/company.py
> +        if not (self.siret or self.vat):
Ah si tu as des tests unitaires pertinents aussi sur la validation du siret, je peux les rajouter, ça mange pas de pain

2024-04-15 13:42 UTC, ddahan commented on frontend/src/stores/createCompany.js
Changé ici 🥳 : https://github.com/betagouv/complements-alimentaires/pull/392/commits/64505ef27311bcf3ec01e4c3f164a49350eed626

2024-04-15 13:44 UTC, ddahan commented on frontend/src/views/CompanyFormPage/Introduction.vue
> +  </DsfrAlert> -->
Ok retiré du coup

2024-04-15 13:45 UTC, ddahan commented on data/models/company.py
> +        if not (self.siret or self.vat):
Changé ici : https://github.com/betagouv/complements-alimentaires/pull/392/commits/463ed55b39c5ddbccfcd75871f354c113e24d85e

2024-04-15 14:13 UTC, alemangui commented on api/views/company.py
> +class CompanyRetrieveView(RetrieveAPIView):
Aaaah my bad, j'au mal lu l'URL

2024-04-15 14:24 UTC, alemangui commented on api/permissions.py
> +class IsSupervisorOfThisCompany(permissions.BasePermission):
Ah oui en effet je ne l'avais pas vu comme ça

2024-04-15 15:01 UTC, alemangui approved these changes

2024-04-15 15:22 UTC, merged