Liste et modification des déclarations
betagouv/complements-alimentaires pull request #397
Opened 2024-04-12 14:42 UTC by alemangui

![image](https://github.com/betagouv/complements-alimentaires/assets/1225929/81740114-4bcf-4d9e-956c-795ec4095ff2)

2024-04-15 07:53 UTC, alemangui commented
Note : Intégrer le composant / endpoint des pays une fois #389 mergée

2024-04-16 09:13 UTC, pletelli requested changes
Des changements mineurs : path en doublon et eventuellement wordinf de "gamme"

2024-04-16 09:13 UTC, pletelli commented on frontend/src/views/ProducerFormPage/SummaryStep.vue
> +  const url = isNew ? "/api/v1/declarations/" : `/api/v1/declarations/${payload.value.id}`
reprendre le meme nom de variable `isNewDeclaration` que dans ProducerFormPage/index.vue ?

2024-04-16 09:13 UTC, pletelli commented on frontend/src/views/ProducerFormPage/index.vue
> +const { response, data, isFetching, execute } = useFetch(`/api/v1/declarations/${props.id}`, { immediate: false })
question noob : je ne suis pas sûre de comprendre pourquoi le immediate est à false.
est-ce "juste" pour pouvoir executer le get seulement si il y a un id (et donc si ce n'est pas une nouvelle déclaration) ?

2024-04-16 14:57 UTC, alemangui commented on api/urls.py
> +    path("declarations/", views.DeclarationListCreateApiView.as_view(), name="create_declaration"),
Mince, merci ! Fix : https://github.com/betagouv/complements-alimentaires/pull/397/commits/e53a73301c74b5dcc8ada25b1316cc6c312c88bc

2024-04-16 14:59 UTC, alemangui commented on frontend/src/views/ProducerFormPage/SummaryStep.vue
> +  const url = isNew ? "/api/v1/declarations/" : `/api/v1/declarations/${payload.value.id}`
Fait par ici : https://github.com/betagouv/complements-alimentaires/pull/397/commits/6c9492b8464ff083568afe7409893cc638f3343b

2024-04-16 15:01 UTC, alemangui commented on api/serializers/declaration.py
> +            "gamme",
En effet, on pourrait éventuellement le renommer dans une autre PR, mais pas sur que ça en vaille la peine

2024-04-16 15:05 UTC, alemangui commented on frontend/src/views/ProducerFormPage/index.vue
> +const { response, data, isFetching, execute } = useFetch(`/api/v1/declarations/${props.id}`, { immediate: false })
Dans ce cas oui c'est bien ça :+1: 

Dans d'autres cas, il faut juste tenir en compte que le code à l'intérieur de `<script setup>` doit être synchrone. Les deux possibilités lors qu'on veut mettre de l'asynchtone c'est soit de mettre le template dans un block `<Suspense>` ([doc](https://vuejs.org/api/sfc-script-setup.html#top-level-await)), soit de mettre le call asynchrone dans le `onMounted` comme c'est fait dans /components/fields/CountryField.vue

2024-04-17 09:57 UTC, pletelli approved these changes

2024-04-17 14:35 UTC, merged