Siret2
betagouv/complements-alimentaires pull request #442
Opened 2024-04-18 17:30 UTC by ddahan

2024-04-18 18:10 UTC, ddahan commented on .pre-commit-config.yaml
Désolé j'ai essayé d'éviter le reformatage du fichier en entier, mais il semble que ce soit "normal" parce qu'il utilise le `.prettierrc` du fichier (cf. screenshot ci-dessous). Peut-être que Alex a un setting vs code personnel qui override le setting du projet ?

<img width="924" alt="image" src="https://github.com/betagouv/complements-alimentaires/assets/1933516/4c02428c-8756-4a26-9aef-027be920393f">

2024-04-25 12:44 UTC, pletelli requested changes

2024-04-25 12:44 UTC, pletelli commented on data/tests/test_external_utils.py
> +        pass  # peu utile à tester réellement car tout serait mocker
mocké ? :D

2024-04-26 08:56 UTC, alemangui commented on .pre-commit-config.yaml
Pas de souci, je regarderai de mon côté si mon env est en train d'overrider qqchose :thinking:

2024-04-26 09:19 UTC, alemangui approved these changes

2024-04-26 09:19 UTC, alemangui commented on frontend/src/views/CompanyFormPage/Identification.vue
Petite correction sur l'URL de la ligne 49, il manque un slash après `check-identifier`, sinon ça nous fait un 301 de la part de Django (ça marche quand même mais ça fait deux requêtes.
```javascript
() => `/api/v1/companies/${identifier.value}/check-identifier/?identifierType=${company.value.identifierType}`
```

Pour éviter : 
![image](https://github.com/betagouv/complements-alimentaires/assets/1225929/73350501-b0ba-4daa-8e18-bc951ecd04e0)

2024-04-26 09:19 UTC, alemangui commented on data/migrations/0059_merge_20240423_1609.py
Si jamais on veut éviter d'avoir plusieurs fichiers de migrations dans une PR (pas obligatoire bien sur), on peut toujours revenir en arrière, supprimer la migration, et relancer un `makemigrations`.

Par ex, disons que j'ajoute un champ dans un modèle et je fais un `manage.py makemigrations`. Cette opération crée une migration type `0054_xxxxx.py`. Puis je refais un autre changement dans le modèle. Pour pas en créer une autre je peux:

1- Revenir en arrière à la 0053 en faisant 
```shell
> manage.py migrate data 0053
[X] 0053_xxx
[ ] 0054_xxx
``` 
2- Supprimer le fichier de migration `0054_xxx`
3- Refaire un `makemigrations` (qui recréera une migration `0054_xxx` mais cette fois-ci contenant les deux changements)
4- Faire un `migrate`

Par contre, une fois le code pushé, il vaut mieux ne pas supprimer les migrations dans le cas où elles auraient déjà été appliquées par une autre personne.

2024-04-26 09:19 UTC, alemangui commented on data/tests/test_external_utils.py
> +    def test_fetch(self):
En effet, p-e qu'on peut le supprimer donc

2024-04-26 09:19 UTC, alemangui commented on fixtures/data.Company.yaml
> -    siret: "08670192700799"
Question juste pour ma culture-g, vu qu'on a un `CharField` derrière ce champ, pourquoi on ne met plus les guillemets ?

2024-04-29 08:01 UTC, ddahan commented on data/utils/external_utils.py
> +            "address": " ".join(filter(None, [adresse[item] for item in address_items])),
Bien vu merci ! J'ai juste un mini-doute que le fait que `complementAdresseEtablissement` corresponde vraiment à "bâtiment, immeuble, escalier et numéro d’appartement" et je galère à trouver un SIRET qui contient ce genre de données pour vérifier. 

Mon doute vient de l'ordre dans lesquels les champs sont listés, qui correspond très probablement à l'ordre d'affichage d'une adresse. Ici ça voudrait dire que `complementAdresseEtablissement` apparait avant l'adresse. Ça m'intrigue.

```
      "adresseEtablissement": {
        "indiceRepetitionDernierNumeroVoieEtablisssement": "string",
        "complementAdresseEtablissement": "string",
        "numeroVoieEtablissement": "string",
        "indiceRepetitionEtablissement": "string",
        "dernierNumeroVoieEtablissement": "string",
        "indiceRepetitionDernierNumeroVoieEtablissement": "string",
        "typeVoieEtablissement": "string",
        "libelleVoieEtablissement": "string",
        "codePostalEtablissement": "string",
        "libelleCommuneEtablissement": "string",
        "libelleCommuneEtrangerEtablissement": "string",
        "distributionSpecialeEtablissement": "string",
        "codeCommuneEtablissement": "string",
        "codeCedexEtablissement": "string",
        "libelleCedexEtablissement": "string",
        "codePaysEtrangerEtablissement": "string",
        "libellePaysEtrangerEtablissement": "string",
        "identifiantAdresseEtablissement": "string",
        "coordonneeLambertAbscisseEtablissement": "string",
        "coordonneeLambertOrdonneeEtablissement": "string"
      },
```

(si on n'a pas la réponse rapidement je vais faire une issue à part)

2024-04-29 08:06 UTC, ddahan commented on frontend/src/views/CompanyFormPage/Identification.vue
Bien vu merci, corrigé. Est-ce que tu penses que du coup ça serait pertinent de mettre [APPEND_SLASH](https://docs.djangoproject.com/en/5.0/ref/settings/#append-slash) à False?

Si je comprends bien, ça ferait en sorte que si j'oublie de mettre le slash moi côté front, j'aurai une 404 plutôt qu'une redirection que je rate peut être.

2024-04-29 08:10 UTC, ddahan commented on data/migrations/0059_merge_20240423_1609.py
Merci beaucoup, je connaissais pas ce trick :) J'essaierai d'y penser la prochaine fois. J'aime pas non plus les migrations inutiles, parce qu'à force ça ralentit le projet (par ex. en lançant les tests sans faire `--keepdb`).

Sur le même sujet, je sais qu'il existe [cette commande](https://docs.djangoproject.com/en/5.0/topics/migrations/#migration-squashing) pour régler le souci des trop nombreuses migrations, mais je t'avoue ne jamais l'avoir fait moi-même en prod 😅

2024-04-29 08:16 UTC, ddahan commented on fixtures/data.Company.yaml
> -    siret: "08670192700799"
Ces fichiers sont écrits automatiquement par Django (commande [dumpdata](https://docs.djangoproject.com/en/5.0/ref/django-admin/#dumpdata) que j'appelle depuis `mydumpdata`).

Je suppose que comme on est sur du fichier plat (yaml, json, etc.), pour être sûr que ma valeur soit pas considérée comme un int, il ajoute automatiquement des guillements pour éviter l'ambiguité. Alors que pour les autres valeurs il n'a pas besoin, car pas d'ambiguité possible.

2024-04-29 08:32 UTC, pletelli approved these changes
Ok en reprenant cette question sur une prochaine PR.

2024-04-29 08:32 UTC, merged