Amélioration de la recherche et ajout de l'autocomplete
betagouv/complements-alimentaires pull request #444
Opened 2024-04-19 12:52 UTC by alemangui

Closes #428

## Logique de la recherche / autocomplete
Sur cette PR, le code des endpoints _search_ et _autocomplete_ sont désormais le mêmes. Le composant utilisé par les deux est aussi le même.

#### Tests _search_ supprimés
La recherche "traditionnelle" était plus sophistiquée (mais moins bonne) que celle de l'autocomplete, du coup certains tests ont été supprimés car ils ne reflètent plus la fonctionnalité actuelle.

2024-04-19 12:53 UTC, alemangui commented on api/serializers/search_result.py
> +    match = serializers.CharField(read_only=True, source="autocomplete_match")
Ce _match_ est utilisé pour montrer le terme (synonym ou name) qui a été pris par le moteur de recherche. On l'affiche pour montrer sous quel terme l'élément est pertinent.

![image](https://github.com/betagouv/complements-alimentaires/assets/1225929/b0e66f1a-ec7d-4a33-95f2-37b01b9fa165)

2024-04-19 12:54 UTC, alemangui commented on api/tests/test_search.py
La fonctionnalité de priorisation de champs n'est plus présent

2024-04-22 13:52 UTC, ddahan approved these changes

2024-04-22 14:13 UTC, alemangui commented on frontend/src/components/ElementAutocomplete.vue
> +  if (error.value) {
Tu as raison, je me le note dans la branche dev que j'ai en ce moment.

Ce code a été copié-collé de _CompositionStep_. Si ma mémoire de poisson rouge ne se trompe pas, je voulais ajouter le `id` au message d'erreur car les appels API se font plusieurs fois à l'endpoint d'autocomplete, et une erreur de serveur pouvait mitrailler la création des messages d'erreur qui s'empilaient. En ajoutant la ligne `id: "autocomplete-error"` je n'avais plus cette situation.

Après c'est qqchose d'assez simple à ajouter par ex en ajoutant un ID du message identique au paramètre `description` dans la fonction `addErrorMessage`.

2024-04-22 14:24 UTC, pletelli commented on api/utils/search.py
> +def search_elements(query, deduplicate=False):
J'avais introduit une différence entre le search et le autocomplete avec ma PR #436 :
* l'autocomplete filtrait les status NOT_AUTHORIZED (cf https://github.com/betagouv/complements-alimentaires/blob/2c4fdc1630f67d62f81de388c4f17de8b92661a4/api/views/autocomplete.py#L46)

Possible d'ajouter un argument `exclude_unauthorized` à la fonction search_elements qui sera True dans le cas de l'utilisation dans le formulaire de déclaration ?
```
def search_elements(query, deduplicate=False, exclude_unauthorized = False) :
```

2024-04-22 14:29 UTC, pletelli requested changes
Je veux bien jute rejeter un coup d'oeil à ta PR quand tu auras fait la modif

2024-04-22 14:41 UTC, alemangui commented on api/utils/search.py
> +def search_elements(query, deduplicate=False):
Ahah on est super synchro : https://github.com/betagouv/complements-alimentaires/pull/444/commits/0b2a5ba8593329377897709af33e869b897d461c

2024-04-22 14:41 UTC, alemangui commented
@pletelli Modif fate. J'en ai profité pour cleaner deux petites lignes côté UI : https://github.com/betagouv/complements-alimentaires/pull/444/commits/0b2a5ba8593329377897709af33e869b897d461c

2024-04-22 15:03 UTC, merged