Sauvegarde des déclarations pour instruction
betagouv/complements-alimentaires pull request #457
Opened 2024-04-23 15:13 UTC by alemangui

2024-04-29 09:15 UTC, pletelli approved these changes
C'est tout bon pour moi une fois le conflit de dépendances résolu.
Je me demande d'ailleurs comment ce conflit est apparu car c'est seulement django-viewflow qui aurait du être ajouté.

2024-04-29 15:29 UTC, ddahan requested changes
Hello ! Très cool, bravo :)
Juste un petit point sur la validation qui me questionne avan validation, et le reste est moins important je pense.
L'utilisation de FSM a l'air sympa. Assez marrant de voir comment ça fonctionne en étant pas directement dans les models.

2024-04-29 15:29 UTC, ddahan commented on pyproject.toml
> +django-viewflow = "^2.0.0"
Pour rester consistent avec la notation des packages existants dans le fichier, j'utiliserais la même notation qu'actuellement : `*` si on est ok pour faire des mises à jour régulières (je pense que oui ici) plutôt que celle par défaut après un `poetry install`.

2024-04-29 15:29 UTC, ddahan commented on requirements.txt
j'avais eu le même "soucis", à savoir des package upgradés alors que c'est pas l'objet de la PR. Je pense que c'est quand on oublie de mettre l'option `--no-update` à un moment.

2024-04-29 15:29 UTC, ddahan commented on api/views/declaration/declaration_flow_validations.py
> +def has_elements(declaration):
Sur cette fonction je changerais 2 petits trucs : 
- la variable `has_elements` qui a le même nom que la fonction m'a fait buggué :D 
- je m'attends à avoir un booléen en retour vu le nom de la fonction, je sais pas trop à quoi correspond la liste vide passée dans le return. Peut être ajouter type hints ou docstring ?

2024-04-29 15:29 UTC, ddahan commented on api/views/declaration/declaration_flow.py
> +    def ensure_validators(self, validators):
Je suppose qu'à terme cette logique pourra être sortie et applicable à d'autres objects quand on en aura ?

2024-04-30 09:11 UTC, alemangui commented on frontend/src/utils/error-handling.js
> +  return {
En vrai je pense qu'on n'avais pas besoin des `fieldErrors` à ce niveau avant. L'objet retourné dans cette fonction avais les fields errors dans la racine, et ce sont ceux là qui permettent la validation dans les formulaires existants, donc pas de souci pour les formulaires existants :+1:

2024-04-30 09:25 UTC, alemangui commented on requirements.txt
Oops !

2024-04-30 09:25 UTC, alemangui commented on api/views/declaration/declaration_flow.py
> +    def ensure_validators(self, validators):
Tout à fait !

2024-04-30 09:45 UTC, alemangui commented on api/views/declaration/declaration_flow_validations.py
> +def has_elements(declaration):
Tu as raison, ce n'est pas clair du tout. J'ai changé les noms de ces fonctions de _has..._ à _validate..._. J'ai aussi ajouté quelques commentaires en haut du fichier pour expliquer et un type-hint pour les fonctions.

https://github.com/betagouv/complements-alimentaires/pull/457/commits/9945cf4494078c5b7a226a464a05e5f4b99520c0

2024-04-30 09:46 UTC, alemangui commented on api/views/__init__.py
> +from .declaration import (  # noqa: F401
Super-Ruff :) https://github.com/betagouv/complements-alimentaires/pull/457/commits/9b41249401dcf66a15da8a5245e52b225982360b

2024-04-30 09:46 UTC, alemangui commented on data/factories/declaration.py
> +    city = factory.Faker("city")
Ajouté par ici https://github.com/betagouv/complements-alimentaires/pull/457/commits/02e7e794aa78707f1d9d7c6645a8e0004456652b

2024-04-30 09:46 UTC, alemangui commented on pyproject.toml
> +django-viewflow = "^2.0.0"
Fix : https://github.com/betagouv/complements-alimentaires/pull/457/commits/225be5f93f8ffc414032af9d7adef4a716dd4b96

2024-04-30 10:53 UTC, alemangui commented on api/views/declaration/declaration.py
> +    permission_classes = [IsDeclarant]
C'est vrai, j'ai ajouté la permission qui vérifie que le droit soit sur une entreprise. Je sais que ce code sera probablement changé lors de ton refacto, mais je préfère l'avoir ici quand même pour ne pas l'oublier : 
https://github.com/betagouv/complements-alimentaires/pull/457/commits/6c21e5ffcddbbfda274474fb1490c00e690df88c

2024-04-30 12:57 UTC, alemangui commented on frontend/src/views/ProducerFormPage/ProductStep.vue
> +    <DsfrInputGroup class="max-w-md" :error-message="externalResults?.company?.[0]" v-else>
Fait par ici : https://github.com/betagouv/complements-alimentaires/pull/457/commits/f548f3bcd4402ee3fb79f7d6c53401963bff9b37

2024-04-30 13:58 UTC, alemangui commented on requirements.txt
@pletelli voilà comment le conflit est apparu :sweat_smile:

2024-04-30 14:26 UTC, merged