Endpoint API : Récupérer toutes les déclarations
betagouv/complements-alimentaires pull request #485
Opened 2024-05-08 09:38 UTC by alemangui

2024-05-17 09:41 UTC, pletelli requested changes
Quelques petites modifs d'orthographe et je reveux bien une explication de l'utilité de `CanAccessUserDeclarations`. Peut-être que tu pourras la rajouter en commentaire ?
:feather:

2024-05-17 09:41 UTC, pletelli commented on api/tests/test_declaration.py
> +    def test_get_all_declarations_non_admin(self):
`non_instructor` au lieu de  `non_admin` qui reste assez impréci ?

2024-05-17 09:41 UTC, pletelli commented on api/utils/filters.py
> +    comme compagnie une de ces trois (IDs 12, 13 ou 14).
~~compagnie~~ entreprise

2024-05-17 09:41 UTC, pletelli commented on api/permissions.py
> +class CanAccessUserDeclatarions(permissions.BasePermission):
~~CanAccessUserDeclatarions~~ CanAccessUserDeclarations

2024-05-17 09:41 UTC, pletelli commented on api/permissions.py
> +class CanAccessUserDeclatarions(permissions.BasePermission):
Je crois que je n'ai pas compris l'intérêt de cette permission en plus de celles qui existent déjà ?

2024-05-20 07:07 UTC, alemangui commented on api/tests/test_declaration.py
> +    def test_get_all_declarations_non_admin(self):
Bien vu ! Fix ici : https://github.com/betagouv/complements-alimentaires/pull/485/commits/e79f2c85d403eaac4b975381f97d3f3ca78c4adc

2024-05-20 07:08 UTC, alemangui commented on api/utils/filters.py
> +    comme compagnie une de ces trois (IDs 12, 13 ou 14).
:+1: https://github.com/betagouv/complements-alimentaires/pull/485/commits/e79f2c85d403eaac4b975381f97d3f3ca78c4adc

2024-05-20 07:10 UTC, alemangui commented on api/permissions.py
> +class CanAccessUserDeclatarions(permissions.BasePermission):
J'ai rajouté un commentaire explicatif ici : https://github.com/betagouv/complements-alimentaires/pull/485/commits/e79f2c85d403eaac4b975381f97d3f3ca78c4adc

En gros, la permission vérifie que l'user identifié soit en train de demander ces propres déclarations. Par exemple, si mon ID est `15` et que je fais une requête pour `/users/15/declarations`, ça doit bien se passer. Par contre, si j'essaie d'obtenir les déclarations de quelqu'un d'autre (genre `/users/25/declarations`) je devrais être bloqué par la permission. D'où la comparaison avec le param de l'URL.

À terme cette permission évoluera, car probablement on voudra que les gestionnaires puissent avoir accès aux déclarations des déclarants de leurs entreprises, etc.

2024-05-20 08:57 UTC, pletelli approved these changes

2024-05-20 08:57 UTC, merged