Changement des model Django pour respecter le modèle de BDD de TeleIcare
betagouv/complements-alimentaires pull request #49
Opened 2023-12-04 17:47 UTC by pletelli

Still todo :

- [ ] Intégrer toutes les tables et leurs relations
- [ ] Faire la commande pour l'import
- [ ] Utiliser `django-import-export` pour permettre l'import de données csv depuis le backoffice

2023-12-06 11:28 UTC, alemangui commented on data/models/substance.py
> +    )  # cette colonne devrat être associée à une unité
Tout à fait d'accord avec ton commentaire. Pour une autre PR, on pourrait jeter un coup d'oeil à [django-measurement](https://pypi.org/project/django-measurement/) pour voir si ça a du sens de l'intégrer ou pas.

2023-12-06 12:51 UTC, alemangui commented on data/raw_data/REF_ICA_AUTREING_SUBSTACTIVE.csv
Question sur ces fichiers : Est-ce OK de les avoir en open-source ? Pas de données qu'on ne voudrait pas exposer ? (par ex les commentaires privés ?)

2023-12-06 15:30 UTC, pletelli commented on data/models/ingredient.py
> +    observation = models.CharField(max_length=200, blank=True)
Oui tu as raison ! Je les ais repris "bêtement" du modèle de données mais c'est cool si on est plus permissifs.
Je vais laisser pour EINECS et CAS.

2023-12-06 15:41 UTC, pletelli commented on data/models/substance.py
> +    qty_to_fill = models.BooleanField()
J'en profite pour renommer `qty_to_fill` en `must_specify_quantity` que je trouve plus compréhensible. Ok pour toi ?

2023-12-06 15:42 UTC, pletelli commented on data/models/population.py
> +            "Groupe de population (cible d'un complément ou à risque d'un ingrédient/substance ou d'un complément)"
Ahah oui :)
Je vais préciser le reste en commentaire.

2023-12-06 15:46 UTC, pletelli commented on data/models/substance.py
> +    )  # cette colonne devrat être associée à une unité
Je fais une issue là dessus !

2023-12-06 16:00 UTC, alemangui commented on data/models/substance.py
> +    qty_to_fill = models.BooleanField()
Top !

2023-12-06 16:01 UTC, pletelli commented on data/raw_data/REF_ICA_AUTREING_SUBSTACTIVE.csv
Et oui ! Tu as complètement raison oO J'ai l'habitude de travailler avec des repo privés. J'enlève ça pour l'instant ...

2023-12-06 16:39 UTC, pletelli commented on data/models/common_base_ingredient.py
> +    # commentaire_public_en = models.CharField(max_length=1000, blank=True)
oui ! c'est amené à disparaître / ou réapparaître sous une autre forme quand on aura une vision encore plus claire des données.

2023-12-06 23:12 UTC, alemangui requested changes

2023-12-06 23:12 UTC, alemangui commented on data/models/common_base_ingredient.py
> +    name_en = models.TextField(blank=True)
```suggestion
    name_en = models.TextField(blank=True, verbose_name="nom en anglais")
```

2023-12-06 23:12 UTC, alemangui commented on data/models/plant.py
> +
Ça pourrait être pour une deuxième PR (celle où l'on ajoutera ces champs dans l'admin par exemple), mais on pourra rajouter les `verbose_name`s pour ces champs aussi pour qu'ils s'affichent en français dans le backoffice.

2023-12-06 23:12 UTC, alemangui commented on data/models/common_base_ingredient.py
> +    public_comments = models.TextField(null=True, blank=True, verbose_name="commentaires publics")
Pour suivre le même standard que les autres, ça t'irait d'avoir seulement le `blank=True` ?
```suggestion
    public_comments = models.TextField(blank=True, verbose_name="commentaires publics")
```

2023-12-06 23:12 UTC, alemangui commented on data/models/common_base_ingredient.py
> +    private_comments = models.TextField(null=True, blank=True, verbose_name="commentaires privés")
```suggestion
    private_comments = models.TextField(blank=True, verbose_name="commentaires privés")
```

2023-12-08 11:26 UTC, alemangui approved these changes

2023-12-08 11:39 UTC, merged