Front-end du tab "Décision"
betagouv/complements-alimentaires pull request #515
Opened 2024-05-23 08:44 UTC by alemangui

Cette PR contient le front-end seulement du tab "Décision". L'idée de le faire séparément est d'avoir un élément visuel pour faire des retours et imaginer le flow avant la modélisation des données.

Suite à une discussion avec @JenniferStephan on a décidé de :
- [x] Enlever l'étape "_Dossier complet_" / "_Dossier incomplet_" qui n'était pas bien compris
- [x] Combiner les deux listes des raisons pour rejet/observation/objection dans une seule
- [x] Garder pour l'instant la liste et la UI de la décision car les chargées de mission ont déjà une mémoire musculaire d'utilisation de ces composants

Par la suite on pourra alléger cette liste en identifiant les options moins utilisées et même automatiquement rédiger le message en dépendant des options choisies. Mais ça viendra dans un second temps.

### Démo

[Screencast from 23-05-24 10:43:02.webm](https://github.com/betagouv/complements-alimentaires/assets/1225929/d3be396f-2f67-49b9-a27c-937e49b22716)

2024-05-29 15:16 UTC, pletelli requested changes
Super d'avoir combiné les deux listes : dossier complet et incomplet.
J'irais quand même encore un peu plus loin dans la simplification (cf mes commentaires).
Si àa peut apporter quelques pistes, je vais sortir les stats d'utilisation des différentes propositions d'examen du dossier dans TeleIcare.

2024-05-29 15:16 UTC, pletelli commented on frontend/src/views/InstructionPage/DecisionTab.vue
> +      "Présence d'un nouvel food",
orthographe :
* "Novel Food" 
* formE d'apport

2024-05-29 15:16 UTC, pletelli commented on frontend/src/views/InstructionPage/DecisionTab.vue
> +      "Présence d'un nouvel food",
La présence d'une forme d'apport en nutriments non autorisée -> ne devrait pas arriver parce que les formes d'apport au status "non autorisé" ne devraient même pas pouvoir sortir comme résultats.
Ou alors on ne fait pas ce pré-filtre sur les status ? Et dans ce cas, on peut automatiquement calculer que le retour à la déclaration sera "Les procédures ne sont pas respectées, présence d'une forme d'apport en nutriments non autorisée".

Idem, pour le retour "Présence d'un Novel Food", j'ai l'impression qu'il faudrait voir avec Emmanuelle si ça ne peut pas être un peu plus précis, car aujourd'hui il y a en base de Novel Food autorisés.
-> transformer en "Présence d'un Novel Food non autorisé" ?

2024-05-29 15:16 UTC, pletelli commented on frontend/src/views/InstructionPage/DecisionTab.vue
> +      "Icohérence entre le dossier et l'étiquetage",
incohérence +N

2024-05-29 15:16 UTC, pletelli commented on frontend/src/views/InstructionPage/DecisionTab.vue
> +      "Absence d'étiquetage",
"Absence d'étiquetage" -> ne devrait plus arriver parce qu'on force l'upload d'une étiquette ?

2024-05-29 15:16 UTC, pletelli commented on frontend/src/views/InstructionPage/DecisionTab.vue
> +              <DsfrInput label="Délai de réponse (jours)" label-visible />
Est-ce que ce délais ne devrait pas être fixe ?
Dans la pratique avez-vous observé qu'elles le renseignaient différemment selon les cas ?
Je suis ok pour qu'on fasse de l'iso, dans la limite où il y a des fonctionnalités un peu bêtes :)

2024-05-29 15:18 UTC, ddahan commented on frontend/src/views/InstructionPage/DecisionTab.vue
> +    description: "La déclaration ne présente pas de problèmes et elle peut être autorisé dans l'état.",
"La déclaration ne pose pas de problème et peut être autorisée en l'état."

2024-05-29 15:19 UTC, ddahan approved these changes
Je trouve ça très clair et intuitif comme ça ! Même pas besoin de formation au nouveau logiciel !

2024-05-29 15:21 UTC, alemangui commented on frontend/src/views/InstructionPage/DecisionTab.vue
> +const rejectReasons = [
Tout à fait, me voilà rassuré que la table existe :)  Vu que cette PR est seulement front je serai partant pour intégrer ces raisons via l'API dans une seconde PR

2024-05-29 15:23 UTC, alemangui commented on frontend/src/views/InstructionPage/DecisionTab.vue
> +      "Absence d'étiquetage",
Je me suis fait la même réflexion mais on pourra forcer que le déclarant.e joigne une pièce jointe mais pas que la pièce jointe contienne l'étiquette (par ex si par erreur il s'agit d'une photo de vacances)

2024-05-29 15:23 UTC, ddahan commented on frontend/src/views/InstructionPage/DecisionTab.vue
> +              <DsfrInput label="Délai de réponse (jours)" label-visible />
Je me posais la même question sur ce délai ...
Doit y'avoir une raison mais là je vois pas.

2024-05-29 15:24 UTC, alemangui commented on frontend/src/views/InstructionPage/DecisionTab.vue
> +              <DsfrInput label="Délai de réponse (jours)" label-visible />
On en a discuté avec les chargées de mission, dans la plupart des cas le délai est 30 jours, mais pour certaines remarques ça peut varier : par ex lors qu'on demande un analyse labo qui prend plus longtemps, ou lorsqu'on est en août, etc

2024-05-29 15:28 UTC, ddahan commented on frontend/src/views/InstructionPage/DecisionTab.vue
> +              <DsfrInput label="Délai de réponse (jours)" label-visible />
Tu vois, ma mémoire est mauvaise :D
Du coup on peut pré-remplir le champ à 30 je suppose ?

2024-05-29 15:33 UTC, ddahan commented on frontend/src/views/InstructionPage/DecisionTab.vue
> +      "Absence d'étiquetage",
Exact (sauf si Perrine peut détecter ça par IA ^^).
Peut être "Étiquetage non conforme" du coup pour clarifier ?

2024-05-29 15:35 UTC, alemangui commented on frontend/src/views/InstructionPage/DecisionTab.vue
> +      "Présence d'un nouvel food",
Tout à fait. Je pense que certaines options ici vont disparaître au fur et à mesure qu'on met les validations côté formulaire du déclarant. Je me demande si _présence d'une forme d'apport en nutriments non autorisée_ pourrait arriver si notre base n'est pas à jour avec la réglementation ou a une erreur ?

2024-05-29 15:36 UTC, alemangui commented on frontend/src/views/InstructionPage/DecisionTab.vue
> +              <DsfrInput label="Délai de réponse (jours)" label-visible />
Tu as raison, d'ailleurs c'est prérempli avec téléicare actuelle :+1:

2024-05-29 15:41 UTC, alemangui commented on frontend/src/views/InstructionPage/DecisionTab.vue
> +              <DsfrInput label="Délai de réponse (jours)" label-visible />
![image](https://github.com/betagouv/complements-alimentaires/assets/1225929/ad76be7c-1c48-4590-a876-39bb0adae26c)
https://github.com/betagouv/complements-alimentaires/pull/515/commits/b31440fd40974cc30444cb94cb0c39089896e1ec :)

2024-05-29 15:43 UTC, alemangui commented on frontend/src/views/InstructionPage/DecisionTab.vue
> +      "Absence d'étiquetage",
https://github.com/betagouv/complements-alimentaires/pull/515/commits/67010e09804aa7a0257630eb7c09b76e6fd3e2b8

2024-05-29 15:43 UTC, alemangui commented on frontend/src/views/InstructionPage/DecisionTab.vue
> +      "Icohérence entre le dossier et l'étiquetage",
https://github.com/betagouv/complements-alimentaires/pull/515/commits/b31440fd40974cc30444cb94cb0c39089896e1ec

2024-05-29 15:43 UTC, alemangui commented on frontend/src/views/InstructionPage/DecisionTab.vue
> +    description: "La déclaration ne présente pas de problèmes et elle peut être autorisé dans l'état.",
https://github.com/betagouv/complements-alimentaires/pull/515/commits/b31440fd40974cc30444cb94cb0c39089896e1ec

2024-05-29 15:46 UTC, ddahan approved these changes

2024-05-30 07:47 UTC, pletelli approved these changes
Parfait ! la suite sera donc https://github.com/betagouv/complements-alimentaires/issues/531

2024-05-30 07:47 UTC, merged