Import des fichiers CSV
betagouv/complements-alimentaires pull request #69
Opened 2023-12-11 17:23 UTC by pletelli

Cette PR : 
* factorise les modèles synonymes et autres dans une classe abstraite
* ajoute le suivi d'historique avec la lib HistoricalRecords

Pas encore : 

* importe les CSV

2023-12-19 23:58 UTC, alemangui requested changes

2023-12-19 23:58 UTC, alemangui commented on data/csv_importer.py
> +    "POPULATION.CSV": Population,
J'imagine qu'on préfère que l'extension soit en minuscule ? 
```suggestion
    "POPULATION.csv": Population,
```
D'ailleurs je n'ai pas trouvé un fichier avec ce nom, j'imagine que c'est `unknown_name_file.csv` dans le commit ?

2023-12-19 23:58 UTC, alemangui commented on files/unknown_name_file.csv
J'imagine que le nom de ce fichier est censé être `POPULATION.csv` ?

2023-12-19 23:58 UTC, alemangui commented on data/migrations/0007_plantfamily_and_more.py
> +        migrations.CreateModel(
Django a cru qu'on voulait créer un nouveau modèle `PlantFamily` et supprimer l'ancien `Family`, ça arrive souvent lorsqu'on modifie le nom et les champs en même temps ([doc à ce sujet](https://docs.djangoproject.com/en/5.0/ref/migration-operations/#renamemodel)).

### Cas d'erreur

Du coup, lors qu'on a déjà des données et qu'on essaie d'appliquer la migration on obtient cette erreur:
```bash
raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration data.old_0008_alter_historicalingredient_private_comments_and_more dependencies reference nonexistent parent node ('data', '0007_plantfamily_and_more')
```
### Possible solution

Dans ces cas, je crée d'abord une migration vide et j'ajoute juste le renommage du modèle.
```bash
python manage.py makemigrations --empty data
```
```python
# 0007_auto_20231220_0031.py
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0006_rename_substance_ingredient_substances_and_more"),
    ]

    operations = [
        migrations.RenameModel("Family", "PlantFamily"),
    ]

```

Après, on peut tranquillement refaire les migrations et Django aura bien compris le renommage du modèle. Cette commande créera la migration _0008_
```bash
python manage.py makemigrations
```
### Combiner les deux migrations

Éventuellement on pourrait fusionner ces deux migrations (_0007_ et _0008_) en un seul fichier (pas obligatoire car [le nombre des migrations sur Django n'est pas un problème](https://docs.djangoproject.com/fr/5.0/topics/migrations/#squashing-migrations), mais peut-être souhaitable car conceptuellement elles font partie du même lot).
```bash
dj squashmigrations data 0007 0008 
```

2023-12-20 14:06 UTC, pletelli commented on data/csv_importer.py
> +                id=row.get(primary_key), defaults=object_definition
Les primary keys seront maintenant celles données dans les csv pour que les relations fonctionnent comme prévu.

2023-12-20 14:06 UTC, pletelli commented on files/POPULATION.csv
> +IDENT,LIBELLE,AGE_MIN,AGE_MAX,CATEGORIE_ANSES
Ce fichier n'a pas été fourni par le SICCRF. C'est pourquoi c'est moi qui ai nommé les colonnes en présageant de ce qu'elles seraient plus tard.

2023-12-21 20:26 UTC, alemangui requested changes

2023-12-21 20:26 UTC, alemangui commented on data/csv_importer.py
> +                id=row.get(primary_key), defaults=object_definition
J'ai laissé un comment à ce sujet un peu plus haut ;)

2023-12-21 20:26 UTC, alemangui commented on data/csv_importer.py
> +def import_csv(csv_filepath):
À mon humble avis, je vois peu d’intérêt à unit-tester chaque fonction car l'import d'un CSV est quelque chose de suffisamment testable dans sa globalité.

J'opterais plutôt pour avoir des tests d'intégration pour cette fonctionnalité, ce qui nous donnerait plus de flexibilité pour adapter ces fonctions si besoin sans devoir re-écrire mille tests. 

Une stratégie serait de créer des sets de fichiers sous _data > tests > files_, Par exemple, si on voulait tester que les modèles sont bien créés pour un set de csvs donné, on pourrait créer le dossier et les fichiers : 
```bash
# Sous data/tests/files/test-model-creation-1
- POPULATION.csv
- REF_ICA_MICRO_ORGANISM.csv
- REF_ICA_PARTIE_PLANTE.csv
- ... etc etc
```
Et dans le test, quelque chose du style
```python
def test_models_created(self):
    path = "./files/test-model-creation-1/"
    call_command("load_ingredients", path...) # Je ne connais pas la syntaxe exacte ^^ 
    self.assertTrue(Plant.objects.get(icare_id=433).exists()
    #... etc etc tous les autres tests concernant ce set
```

2023-12-21 20:26 UTC, alemangui commented on data/csv_importer.py
> +        except KeyError as e:
Question plus générale... Comment veut-on gérer l'échec d'une ligne ? Sauf erreur de ma part, aujourd'hui on log l'erreur et on continue la création des autres modèles.

Une alternative serait de tout stopper lors qu'on rencontre une erreur (en englobant par exemple d'un `@transaction.atomic` le command). Comme ça si on a des erreurs et on re-tente le fichier x fois, on ne ferait pas d'opérations partielles (des updates des lignes qui marchaient bien à chaque tentative, des sauvegardes partielles où des modèles en foreign-key pourraient ne pas exister, etc).

T'en penses quoi ?

2023-12-27 09:07 UTC, pletelli commented on data/csv_importer.py
> +                        object_definition[field.name] = linked_model.objects.get(pk=foreign_key_id)
J'aime beaucoup cette proposition d'un id par système !

2023-12-27 09:08 UTC, pletelli commented on data/csv_importer.py
> +            for field, column_name in django_fields_to_column_names.items():
Oui

2023-12-27 09:09 UTC, pletelli commented on data/csv_importer.py
> +        logger.error(f"'{csv_filename}' n'est pas un fichier csv.")
C'est noté pour la prochaine PR ! Merci.

2023-12-27 09:09 UTC, pletelli commented on data/admin/__init__.py
> +admin.site.register(Substance)
Géré lors du merge.

2023-12-27 09:56 UTC, pletelli commented on data/csv_importer.py
> +def import_csv(csv_filepath):
Oui en effet :) Merci !

2023-12-27 09:59 UTC, pletelli commented on data/csv_importer.py
> +        except KeyError as e:
Oui aujourd'hui c'est seulement loggé.
C'est une bonne question.
J'ai l'impression que c'est une stratégie qu'on pourrait adopter pour des imports moins stables (peut-être world flora, ou d'autres bdd crowdsourcées...).
Je note dans les sujets à discuter ensemble !

2023-12-27 13:27 UTC, pletelli commented on data/csv_importer.py
> +                        object_definition[field.name] = linked_model.objects.get(pk=foreign_key_id)
Implémenté dans les models et factory ici https://github.com/betagouv/complements-alimentaires/pull/69/commits/c9ded8271589346a6ccfffd5fd4af4e47b2a3948
Utilisé dans l'import ici https://github.com/betagouv/complements-alimentaires/pull/69/commits/f8f937f3f71e541d3baa2e85cf9d9b98023eff08

Je me suis posé la question de faire plutôt 2 champs :
* external_id
* external_id_source (dans 'SICCRF', 'WorldFlora', etc)

Mais on pourra toujours améliorer ça plus tard.

2023-12-27 14:29 UTC, pletelli commented on data/csv_importer.py
> +def import_csv(csv_filepath):
C'est fait ici : https://github.com/betagouv/complements-alimentaires/pull/69/commits/cd198269c0dc47cdc30d127bb298f84d335f1ea1

2023-12-27 14:30 UTC, merged