Backoffice : Ajout des ingrédients de base dans l'interface d'admin
betagouv/complements-alimentaires pull request #71
Opened 2023-12-13 15:28 UTC by pletelli

2023-12-21 19:04 UTC, alemangui requested changes

2023-12-21 19:04 UTC, alemangui commented on data/admin/substance.py
> +        ("name", "name_en"),
Un inconvénient de regrouper des champs de cette façon est qu'ils s'affichent horizontalement - ce qui peut-être utile pour des petits champs liés mais qui risque de cacher les champs plus grands.

Par ex, sur mon écran avec le navigateur en entier je n'arrive pas à voir la totalité des deux champs (certes, j'ai un petit écran ^^) et bizarrement je n'ai pas de scroll horizontal. Si une personne travaille avec la fenêtre du navigateur en mi-écran certains champs pourraient être hors la vue.

![image](https://github.com/betagouv/complements-alimentaires/assets/1225929/f68b152a-9995-4d59-b23f-8b09e5b63bd2)

Une alternative pour regrouper des champs est l'utilisation des [fieldsets](https://docs.djangoproject.com/en/5.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.fieldsets). Genre en inventant un peu :

```python
fieldsets = [
        (
            None,
            {
                "fields": ["name", "name_en", "is_obsolete", "source"],
            },
        ),
        (
            "Commentaires",
            {
                "fields": ["public_comments", "private_comments"],
            },
        ),
        (
            "Quantités",
            {
                "fields": ["must_specify_quantity", "min_quantity", ...],
            },
        ),
       ...
```

Qu'est-ce que t'en penses ?

2023-12-22 11:16 UTC, pletelli commented on data/admin/substance.py
> +        ("name", "name_en"),
Ahah oui j'avais la volonté de les aligner horizontalement (pour ne pas avoir à scroller verticalement pour avoir l'aperçu entier des substances) mais tu as raison ce n'est vraiment pas responsive.
Mon écran lui est large mais pas très haut :D

2023-12-22 11:27 UTC, pletelli commented on data/admin/substance.py
> +        ("name", "name_en"),
![image](https://github.com/betagouv/complements-alimentaires/assets/1618987/42a7b00a-f74f-43b1-a743-e90ec3ff8c30)
Tout petit écran
![image](https://github.com/betagouv/complements-alimentaires/assets/1618987/53f6808c-213d-474a-ae71-8c2616c84168)

2023-12-22 11:34 UTC, merged